#!/usr/bin/env bash
# IUT 系3.12 形式検証のビルド + 公理チェック
# 必要: elan (https://github.com/leanprover/elan)
set -euo pipefail
cd "$(dirname "$0")"

lake build

# sorry や追加公理に依存していないことを確認
cat > /tmp/iut_check_axioms.lean <<'EOF'
import IUT
#print axioms IUT.verdict
#print axioms IUT.ss_incompatible
#print axioms IUT.cor312_independent
#print axioms IUT.controversy_reduces_to_rc
#print axioms IUT.mono_implies_bi
#print axioms IUT.bi_implies_mono_classical
#print axioms IUT.AddSym.act_comp
#print axioms IUT.theta_labels
#print axioms IUT.path_col
#print axioms IUT.cross_col_needs_theta
#print axioms IUT.abc_implies_asymptotic_fermat
#print axioms IUT.szpiro_of_cor312
#print axioms IUT.szpiro_of_cor312_precise
#print axioms IUT.cor312_of_multiradial
#print axioms IUT.strict_evaluation_obstruction
#print axioms IUT.padding_necessary
#print axioms IUT.multiradial_consistent
#print axioms IUT.gaussian_obstruction
#print axioms IUT.szpiro_of_multiradial
#print axioms IUT.recon_log_compat
#print axioms IUT.addSym_inverse
#print axioms IUT.bicoric_constant
#print axioms IUT.theta_value_pm_symmetry
#print axioms IUT.two_mul_procTotal
#print axioms IUT.height_bounded_of_uniform_szpiro
#print axioms IUT.abc_bounds_catalan23
#print axioms IUT.six_mul_sumSq
#print axioms IUT.invariant_transport
#print axioms IUT.geometric_normal
#print axioms IUT.outer_conjugation_unique
#print axioms IUT.outer_action_inner_on_kernel
#print axioms IUT.slim_faithful
#print axioms IUT.section_decomposition
#print axioms IUT.theta_deck_not_finite
#print axioms IUT.theta_exponent_unique
#print axioms IUT.theta_exponent_not_periodic
#print axioms IUT.finite_quotient_collapses_theta
#print axioms IUT.arithmetic_quotient_collapses_theta
#print axioms IUT.temperedArithmetic_consistent
#print axioms IUT.tempered_invariant_transport
#print axioms IUT.findWitness_spec
#print axioms IUT.abelianization_determines
#print axioms IUT.reconCore_correct
#print axioms IUT.padic_recon_monoanabelian
#print axioms IUT.padic_recon_bianabelian
#print axioms IUT.padic_invariant_transport
#print axioms IUT.cyclotome_indeterminacy
#print axioms IUT.marked_cyclotome_rigid
#print axioms IUT.theta_comm
#print axioms IUT.mono_theta_cyclotomic_rigidity
#print axioms IUT.rigid_theta_values
#print axioms IUT.Frobenioid.deg_zero
#print axioms IUT.frob_not_invertible
#print axioms IUT.gaussianDiv_deg
#print axioms IUT.frobenioid_realizes_qpilot
#print axioms IUT.degree_volume_consistent
#print axioms IUT.GrpCong.inv_compat
#print axioms IUT.quot_exact
#print axioms IUT.quot_universal
#print axioms IUT.limit_universal
#print axioms IUT.toZhat_injective
#print axioms IUT.zmod_bounded_exponent
#print axioms IUT.zmod_collapses_theta
#print axioms IUT.equivariant_is_right_mul
#print axioms IUT.fiber_functor_recovers_group
#print axioms IUT.level_transition_equivariant
#print axioms IUT.galois_closure
#print axioms IUT.genOpen_minimal
#print axioms IUT.continuous_into_gen
#print axioms IUT.limitProj_continuous
#print axioms IUT.limit_mul_continuous
#print axioms IUT.limit_inv_continuous
#print axioms IUT.projKernel_isOpen
#print axioms IUT.cylinder_nbhd_basis
#print axioms IUT.projKernel_nbhd
#print axioms IUT.zhat_proj_surjective
#print axioms IUT.cosetAction
#print axioms IUT.orbit_stabilizer
#print axioms IUT.orbit_transitive
#print axioms IUT.every_orbit_is_coset
#print axioms IUT.coset_hom_iff
#print axioms IUT.levelAction_smooth
#print axioms IUT.levelAction_stabilizer_open
#print axioms IUT.pigeonhole
#print axioms IUT.card_unique
#print axioms IUT.finite_bounded_exponent
#print axioms IUT.zmod_finite
#print axioms IUT.zmod_listable
#print axioms IUT.listable_discrete_compact
#print axioms IUT.zmod_compact
#print axioms IUT.compact_image
#print axioms IUT.compact_prod
#print axioms IUT.restrictEquiv
#print axioms IUT.skel_classification
#print axioms IUT.fiberAut
#print axioms IUT.from_to
#print axioms IUT.to_from
#print axioms IUT.sga1Equivalence
#print axioms IUT.gsets_G1_final
#print axioms IUT.gsets_G1_pullback
#print axioms IUT.gsets_G2_initial
#print axioms IUT.gsets_G2_sum
#print axioms IUT.gsets_G3_factorization
#print axioms IUT.gsets_G4_forgetful_preserves_pullback
#print axioms IUT.gsets_G5_forgetful_preserves_sum
#print axioms IUT.gsets_G6_reflects_iso
#print axioms IUT.GaloisCatData.eq_mono
#print axioms IUT.GaloisCatData.feq_surj
#print axioms IUT.GaloisCatData.fiber_faithful
#print axioms IUT.GaloisCatData.mono_of_fiber_injective
#print axioms IUT.GaloisCatData.evaluation_injective
#print axioms IUT.GaloisCatData.galois_evaluation_bijective
#print axioms IUT.gsetGaloisData
#print axioms IUT.galoisCatData_consistent
#print axioms IUT.CatIso.ext
#print axioms IUT.GaloisCatData.autGrp
#print axioms IUT.GaloisCatData.homFunctor
#print axioms IUT.GaloisCatData.homFunctor_faithful
#print axioms IUT.GaloisCatData.connected_hom_surjective
#print axioms IUT.GaloisCatData.split_connected_transitive
#print axioms IUT.DescentData.homFunctor_full
#print axioms IUT.DescentData.sga1_fully_faithful
#print axioms IUT.gsetDescentData
#print axioms IUT.descentData_consistent
#print axioms IUT.Grp.mul_inv_cancel_left
#print axioms IUT.QuotientData.quotient_realizes_coset
#print axioms IUT.QuotientData.sga1_essentially_surjective
#print axioms IUT.gsetQuotientData
#print axioms IUT.quotientData_consistent
#print axioms IUT.GaloisCatData.aut_transition_exists_unique
#print axioms IUT.GaloisCatData.aut_transition_surjective
#print axioms IUT.GaloisTower.transAut_mul
#print axioms IUT.GaloisTower.towerSystem
#print axioms IUT.GaloisTower.pi1Tower
#print axioms IUT.GaloisTower.pi1Tower_mul_continuous
#print axioms IUT.unitAction_galois
#print axioms IUT.galoisTower_consistent
#print axioms IUT.assemble_level
#print axioms IUT.refine_step
#print axioms IUT.natSystem_compact
#print axioms IUT.pi1Tower_compact
#print axioms IUT.factChain_compact
#print axioms IUT.SumData.connected_factors
#print axioms IUT.SumData.hom_sum_realizes
#print axioms IUT.SumData.sum_decomposition
#print axioms IUT.gsetSumData
#print axioms IUT.sumData_consistent
#print axioms IUT.Zp
#print axioms IUT.Zp_compact
#print axioms IUT.Zp_mul_continuous
#print axioms IUT.toZp_injective
#print axioms IUT.unramifiedRec
#print axioms IUT.unramifiedRec_kernel
#print axioms IUT.unramifiedRec_level_surj
#print axioms IUT.unramifiedLocalCFT
#print axioms IUT.localCFT_consistent
#print axioms IUT.map_le_iff_le_comap
#print axioms IUT.comap_map_of_injective
#print axioms IUT.norm_correspondence
#print axioms IUT.unramified_norm_correspondence
#print axioms IUT.dvd_sub_mul
#print axioms IUT.zpMul
#print axioms IUT.zpMul_comm
#print axioms IUT.geom_identity
#print axioms IUT.zmod_principal_unit_invertible
#print axioms IUT.dvd_sub_geomSum
#print axioms IUT.geomSum_levels
#print axioms IUT.isPrincipalUnit_mul
#print axioms IUT.zpGeomInv
#print axioms IUT.principalUnits
#print axioms IUT.principalUnits_comm
#print axioms IUT.principal_unit_invertible
#print axioms IUT.toZp_one_add_principal
#print axioms IUT.unitFiltration
#print axioms IUT.unitFiltration_full
#print axioms IUT.unitFiltration_antitone
#print axioms IUT.unitFiltration_separated
#print axioms IUT.levelTheta
#print axioms IUT.unitTheta_hom
#print axioms IUT.unitTheta_kernel
#print axioms IUT.unitTheta_surj
#print axioms IUT.succ_mul_chs
#print axioms IUT.bezout
#print axioms IUT.euclid
#print axioms IUT.isPrime_two
#print axioms IUT.isPrime_three
#print axioms IUT.prime_dvd_chs
#print axioms IUT.binomial
#print axioms IUT.freshman
#print axioms IUT.fermat_little
#print axioms IUT.pow_sub_factor
#print axioms IUT.pow_lift
#print axioms IUT.teich_step
#print axioms IUT.teich
#print axioms IUT.teich_reduction
#print axioms IUT.teich_mul
#print axioms IUT.teich_one
#print axioms IUT.teich_frobenius
#print axioms IUT.zpPow
#print axioms IUT.zpPow_succ
#print axioms IUT.euclid_int
#print axioms IUT.flt_unit
#print axioms IUT.euler_pow
#print axioms IUT.teich_root_of_unity
#print axioms IUT.teich_invertible
#print axioms IUT.zpMul_assoc
#print axioms IUT.zpOne_mul
#print axioms IUT.isPrincipalUnit_of_level_one
#print axioms IUT.teich_congr
#print axioms IUT.unit_decomposition
#print axioms IUT.decomposition_unique
#print axioms IUT.not_dvd_ipow
#print axioms IUT.isZpUnit_mul
#print axioms IUT.isZpUnit_teich
#print axioms IUT.isZpUnit_of_principal
#print axioms IUT.unit_pow_principal
#print axioms IUT.zpUnitInv_mul
#print axioms IUT.zpUnits
#print axioms IUT.zpUnits_comm
#print axioms IUT.zpUnits_decomposition
#print axioms IUT.prodHom_injective
#print axioms IUT.recQp
#print axioms IUT.recQp_injective
#print axioms IUT.recQp_units_to_inertia
#print axioms IUT.fullLocalCFT
#print axioms IUT.fullLocalCFT_consistent
#print axioms IUT.CRing.right_distrib
#print axioms IUT.CRing.mul_zero
#print axioms IUT.CRing.toGrp
#print axioms IUT.intRing
#print axioms IUT.zmodRing
#print axioms IUT.zpRing
#print axioms IUT.toZpRing
#print axioms IUT.projRing
#print axioms IUT.rsum_add
#print axioms IUT.rsum_reflect
#print axioms IUT.rsum_triangle
#print axioms IUT.psRing
#print axioms IUT.psConstHom
#print axioms IUT.rsum_single
#print axioms IUT.psPow_add
#print axioms IUT.psPow_coeff_zero
#print axioms IUT.psComp_add
#print axioms IUT.psComp_one
#print axioms IUT.psComp_X
#print axioms IUT.psComp_coeff_zero
#print axioms IUT.psComp_coeff_one
#print axioms IUT.CRing.add_quad_swap
#print axioms IUT.psPow_congr
#print axioms IUT.psPow_coeff_diag
#print axioms IUT.psPow_coeff_congr
#print axioms IUT.lubin_tate_unique
#print axioms IUT.CRing.cancel_to_annihilate
#print axioms IUT.zp_p_regular
#print axioms IUT.zp_unit_regular
#print axioms IUT.zp_lt_cancel
#print axioms IUT.lubin_tate_unique_zp
#print axioms IUT.zpDivP
#print axioms IUT.zpDivP_mul_cancel
#print axioms IUT.zpDivP_cancel
#print axioms IUT.zp_dvd_p_iff
#print axioms IUT.zp_flt
#print axioms IUT.zp_frobenius_divisible
#print axioms IUT.rofNat_add
#print axioms IUT.rofNat_mul
#print axioms IUT.binomial2
#print axioms IUT.rofNat_chs_factor
#print axioms IUT.freshman_ring
#print axioms IUT.freshman_ps
#print axioms IUT.psC_mul_coeff
#print axioms IUT.rofNat_zp
#print axioms IUT.freshman_zp
#print axioms IUT.ringHom_rsum
#print axioms IUT.psMap_mul
#print axioms IUT.psMap_comp
#print axioms IUT.psMono_mul
#print axioms IUT.psMono_pow
#print axioms IUT.psComp_mono_coeff
#print axioms IUT.psComp_mono_coeff_zero
#print axioms IUT.zmod_flt
#print axioms IUT.freshman_exact
#print axioms IUT.psSingle_pow
#print axioms IUT.psComp_single
#print axioms IUT.frobenius_trunc
#print axioms IUT.frobenius_charp
#print axioms IUT.ltPoly_coeff_zero
#print axioms IUT.ltPoly_coeff_one
#print axioms IUT.ltPoly_reduction
#print axioms IUT.ltError_reduction
#print axioms IUT.ltError_divisible
#print axioms IUT.ltSol
#print axioms IUT.ltSeg_eq_sol
#print axioms IUT.ltSol_div
#print axioms IUT.ltSol_equation
#print axioms IUT.lubin_tate_exists
#print axioms IUT.lubin_tate
#print axioms IUT.elementaryFrobenioid
#print axioms IUT.degFunctor
#print axioms IUT.frobFunctor
#print axioms IUT.frob_no_right_inverse
#print axioms IUT.iso_deg_one
#print axioms IUT.iso_objects_eq
#print axioms IUT.hom_exists_but_no_iso
#print axioms IUT.degMor
#print axioms IUT.frobFunctor_matches_frob
#print axioms IUT.deg_frobFunctor
#print axioms IUT.rsum_psRing_coeff
#print axioms IUT.ps2Pow_tcoeff_zero
#print axioms IUT.ps2Comp1_add
#print axioms IUT.ps2Comp1_one
#print axioms IUT.ps2Comp1_X
#print axioms IUT.ps2Lin_00
#print axioms IUT.ps2Lin_10
#print axioms IUT.ps2Lin_01
#print axioms IUT.psPow_psC
#print axioms IUT.ps2X_pow
#print axioms IUT.ps2Y_pow
#print axioms IUT.ps2MonoXY
#print axioms IUT.ps2Comp2_coords
#print axioms IUT.ps2Comp1_coordX
#print axioms IUT.ps2Comp1_coordY
#print axioms IUT.psMap_constHom_psX
#print axioms IUT.fgl_equation_identity
#print axioms IUT.inX_ltPoly_00
#print axioms IUT.inY_ltPoly_00
#print axioms IUT.degZ_add
#print axioms IUT.degZ_frob
#print axioms IUT.rationalFrobenioid
#print axioms IUT.rational_frob_not_invertible
#print axioms IUT.rational_gaussian_deg
#print axioms IUT.rationalDegVol
#print axioms IUT.rational_qpilot_volume
#print axioms IUT.degZ_single_valuation
#print axioms IUT.divisorFrobenioid
#print axioms IUT.divDegFunctor
#print axioms IUT.divisor_iso_objects_eq
#print axioms IUT.divisor_iso_deg_eq
#print axioms IUT.divisor_hom_exists_but_no_iso
#print axioms IUT.psRingHom
#print axioms IUT.ps2Map_X
#print axioms IUT.ps2Map_Y
#print axioms IUT.ps2Map_comp1
#print axioms IUT.ps2Map_comp2
#print axioms IUT.ps2Map_psC
#print axioms IUT.ps2Map_inY
#print axioms IUT.ps2Map_equation
#print axioms IUT.ltFormalGroup_reduction
#print axioms IUT.ltFormalGroup_reduction_linear
#print axioms IUT.isoUnique_subsingleton
#print axioms IUT.divisorFrobenioid_gaunt
#print axioms IUT.divisor_iso_is_id
#print axioms IUT.divisorFrobenioid_iso_unique
#print axioms IUT.divisorFrobenioid_rigid
#print axioms IUT.elementaryFrobenioid_gaunt
#print axioms IUT.elementary_iso_unique
#print axioms IUT.deloop_every_hom_iso
#print axioms IUT.deloop_aut_torsor
#print axioms IUT.deloop_gaunt
#print axioms IUT.deloop_not_iso_unique
#print axioms IUT.gaunt_dichotomy
#print axioms IUT.deloop_intGrp_not_iso_unique
#print axioms IUT.deloopInd_nontrivial
#print axioms IUT.freshman_exact_ring
#print axioms IUT.frobHom
#print axioms IUT.freshman_exact_gen
#print axioms IUT.psMap_trunc
#print axioms IUT.frobenius_trunc_gen
#print axioms IUT.frobenius_charp_gen
#print axioms IUT.frobenius_gen_recovers
#print axioms IUT.psRing_char
#print axioms IUT.ps2Comp1_mono
#print axioms IUT.ps2_powXY
#print axioms IUT.ps2Comp2_powXY_hit
#print axioms IUT.ps2Comp2_powXY_missY
#print axioms IUT.ps2Comp2_powXY_missX
#print axioms IUT.ps2Pow_frob_hit
#print axioms IUT.ps2Pow_frob_missY
#print axioms IUT.ps2Pow_frob_missX
#print axioms IUT.frobenius2_charp
#print axioms IUT.lt_error_vanishes_modp
#print axioms IUT.lt_error_vanishes_modp'
#print axioms IUT.lt2Err_zero_iff_equation
#print axioms IUT.ps2Map_zero_cond
#print axioms IUT.lt2Err_reduction
#print axioms IUT.lt2Err_divisible
#print axioms IUT.lt2Div
#print axioms IUT.lt2Div_cancel
#print axioms IUT.gpow_add
#print axioms IUT.gpow_mul
#print axioms IUT.gpow_mul_dist
#print axioms IUT.splitFrobenioid
#print axioms IUT.splitForget
#print axioms IUT.unit_endo_comp
#print axioms IUT.splitForget_unit
#print axioms IUT.split_iso_objects_eq
#print axioms IUT.splitFrobenioid_gaunt
#print axioms IUT.split_iso_unit_arbitrary
#print axioms IUT.split_polyiso_torsor
#print axioms IUT.split_not_iso_unique
#print axioms IUT.split_forget_mapIso_eq
#print axioms IUT.split_dichotomy_refined
#print axioms IUT.splitInd_nontrivial
#print axioms IUT.ps2Mul_coeff
#print axioms IUT.ps2Pow_one
#print axioms IUT.ps2Mul_coeff_congr
#print axioms IUT.ps2Pow_coeff_congr
#print axioms IUT.ps2Pow_coeff_congr'
#print axioms IUT.ps2Comp1_single_one
#print axioms IUT.lt2_lhs_decomp
#print axioms IUT.inX_mul_inY
#print axioms IUT.lt2_rhs_coeff
#print axioms IUT.discCat
#print axioms IUT.localFrobenioid
#print axioms IUT.localToElementary
#print axioms IUT.fiberedFrobenioid
#print axioms IUT.fibProj
#print axioms IUT.fibProj_endo_id
#print axioms IUT.no_cross_prime_hom
#print axioms IUT.fiberIncl
#print axioms IUT.fiber_local_iso
#print axioms IUT.divRestrictFunctor
#print axioms IUT.restrict_determines
#print axioms IUT.fibered_iso_objects_eq
#print axioms IUT.fiberedFrobenioid_gaunt
#print axioms IUT.fibered_iso_unique
#print axioms IUT.fibered_rigid
#print axioms IUT.rsum_single_diff
#print axioms IUT.ltPow_low
#print axioms IUT.ltPow_diag
#print axioms IUT.lt2_rhs_split
#print axioms IUT.rpow_add
#print axioms IUT.lt2Sol
#print axioms IUT.lt2Seg_stable
#print axioms IUT.lt2Seg_eq_sol
#print axioms IUT.lt2Seg_high
#print axioms IUT.lt2Sol_div
#print axioms IUT.lt2Sol_equation
#print axioms IUT.lt2Sol_is_formal_group
#print axioms IUT.lt_formal_group_exists
#print axioms IUT.splitFiberedFrobenioid
#print axioms IUT.sfForgetUnit
#print axioms IUT.sfProj
#print axioms IUT.sfProj_onHom_factor
#print axioms IUT.localSplitFrobenioid
#print axioms IUT.sfFiberIncl
#print axioms IUT.sf_fiber_local_iso
#print axioms IUT.sf_iso_objects_eq
#print axioms IUT.splitFiberedFrobenioid_gaunt
#print axioms IUT.sf_polyiso_torsor
#print axioms IUT.sf_forget_mapIso_eq
#print axioms IUT.sf_not_iso_unique
#print axioms IUT.sf_dichotomy
#print axioms IUT.lt_formal_group_unique
#print axioms IUT.lt_formal_group_exists_unique
#print axioms IUT.rsum_exchange
#print axioms IUT.swap_mul
#print axioms IUT.swap_pow
#print axioms IUT.swap_comp1
#print axioms IUT.swap_rhs
#print axioms IUT.swap_is_formal_group
#print axioms IUT.lt_formal_group_comm
#print axioms IUT.lt2Sol_comm
#print axioms IUT.towerCat
#print axioms IUT.tower_nontrivial
#print axioms IUT.tower_no_descent
#print axioms IUT.ramifiedFrobenioid
#print axioms IUT.ramProj
#print axioms IUT.ramProj_vertical_id
#print axioms IUT.ramVerticalIncl
#print axioms IUT.ramVerticalIncl_faithful
#print axioms IUT.ramVerticalIncl_full
#print axioms IUT.pullbackFunctor
#print axioms IUT.pullback_deg
#print axioms IUT.ramPullbackMor
#print axioms IUT.ramProj_pullbackMor
#print axioms IUT.ram_hom_factor
#print axioms IUT.pullback_incl_compat
#print axioms IUT.ram_iso_e_one
#print axioms IUT.ram_iso_objects_eq
#print axioms IUT.ramifiedFrobenioid_gaunt
#print axioms IUT.ram_iso_unique
#print axioms IUT.ram_rigid
#print axioms IUT.ram_no_descent
#print axioms IUT.pullback_not_invertible
#print axioms IUT.ramSplitFrobenioid
#print axioms IUT.rsForgetUnit
#print axioms IUT.rsProj
#print axioms IUT.rsProj_onHom_factor
#print axioms IUT.rsPullbackMor
#print axioms IUT.rsProj_pullbackMor
#print axioms IUT.rs_hom_factor
#print axioms IUT.rs_iso_e_one
#print axioms IUT.rs_iso_objects_eq
#print axioms IUT.ramSplitFrobenioid_gaunt
#print axioms IUT.rsUnitIso
#print axioms IUT.rs_polyiso_torsor
#print axioms IUT.rs_forget_mapIso_eq
#print axioms IUT.rs_not_iso_unique
#print axioms IUT.rs_dichotomy
#print axioms IUT.rs_pullback_not_invertible
#print axioms IUT.RingHom.comp
#print axioms IUT.ps3Lin_000
#print axioms IUT.ps3Lin_001
#print axioms IUT.ps3Lin_010
#print axioms IUT.ps3Lin_100
#print axioms IUT.ps3Mul_coeff
#print axioms IUT.ps3Pow_tcoeff_zero
#print axioms IUT.ps3Comp1
#print axioms IUT.in3X_000
#print axioms IUT.in3Y_000
#print axioms IUT.in3Z_000
#print axioms IUT.ps3Comp3
#print axioms IUT.ps3Lin_linear_conditions
#print axioms IUT.ps3Pow_one
#print axioms IUT.ps3Mul_coeff_congr
#print axioms IUT.ps3Pow_coeff_congr
#print axioms IUT.ps3Pow_coeff_congr'
#print axioms IUT.ps3Comp1_add
#print axioms IUT.ps3Comp1_single_one
#print axioms IUT.ps3Comp1_mono
#print axioms IUT.lt3_lhs_decomp
#print axioms IUT.in3X_pow
#print axioms IUT.in3Y_pow
#print axioms IUT.in3Z_pow
#print axioms IUT.in3X_mul_in3Y
#print axioms IUT.ps3_constV_mul_inZ
#print axioms IUT.lt3_rhs_coeff
#print axioms IUT.lt3_rhs_split
#print axioms IUT.lt3_unique
#print axioms IUT.ps23Comp
#print axioms IUT.ps3Mul_deg1_zero
#print axioms IUT.ps23Comp_000
#print axioms IUT.ps23Comp_lin
#print axioms IUT.assocL
#print axioms IUT.assocR
#print axioms IUT.assocL_000
#print axioms IUT.assocR_000
#print axioms IUT.assocL_linear
#print axioms IUT.assocR_linear
#print axioms IUT.ps3Mul_low_zero
#print axioms IUT.ps3PowPow_low
#print axioms IUT.liftXY_mul
#print axioms IUT.liftXY_pow
#print axioms IUT.liftXY_comp1
#print axioms IUT.liftYZ_mul
#print axioms IUT.liftYZ_pow
#print axioms IUT.liftYZ_comp1
#print axioms IUT.ps3X_eq_in3X
#print axioms IUT.ps3Y_eq_in3Y
#print axioms IUT.ps3Z_eq_in3Z
#print axioms IUT.ps3Comp1_in3X
#print axioms IUT.ps3Comp1_in3Y
#print axioms IUT.ps3Comp1_in3Z
#print axioms IUT.rsum_pad
#print axioms IUT.ps3_const_mul
#print axioms IUT.ps3Smul_eq
#print axioms IUT.ps3Fam_congr
#print axioms IUT.ps3Fam_mul_right
#print axioms IUT.ps3Fam_mul_left
#print axioms IUT.ps3Smul_rsum
#print axioms IUT.ps3Mul_congr_le
#print axioms IUT.CRing.mul_mul_comm
#print axioms IUT.ps3PowPow_mul
#print axioms IUT.ps3Const_mul
#print axioms IUT.ps3Smul_mul_smul
#print axioms IUT.ps23Comp_eq_fam
#print axioms IUT.quad_sum_reindex
#print axioms IUT.ps23Comp_mul
#print axioms IUT.ps23Comp_one
#print axioms IUT.ps23Comp_add
#print axioms IUT.ps2Mul_low_zero
#print axioms IUT.ps2PowPow_low
#print axioms IUT.ps23Comp_pow
#print axioms IUT.ps23Comp_comp1
#print axioms IUT.ps2Comp2_pad
#print axioms IUT.ps23Comp_comp2
#print axioms IUT.psX_pow_coeff
#print axioms IUT.psComp_X_right
#print axioms IUT.ps23Comp_inX
#print axioms IUT.ps23Comp_inY
#print axioms IUT.ps3Comp1_ps3X
#print axioms IUT.ps3Comp1_ps3Y
#print axioms IUT.ps3Comp1_ps3Z
#print axioms IUT.ps3TriplePow_low
#print axioms IUT.ps3TriplePow_mul
#print axioms IUT.ps3Comp3_eq_fam
#print axioms IUT.hex_sum_reindex
#print axioms IUT.ps3Comp3_mul
#print axioms IUT.ps3Comp3_one
#print axioms IUT.ps3Comp3_pow
#print axioms IUT.ps3Comp1_X
#print axioms IUT.ps23Comp_X
#print axioms IUT.ps23Comp_Y
#print axioms IUT.ps3Comp3_liftXY
#print axioms IUT.ps3Comp3_liftYZ
#print axioms IUT.liftXY_comp2
#print axioms IUT.liftYZ_comp2
#print axioms IUT.liftYZ_in2X
#print axioms IUT.liftYZ_in2Y
#print axioms IUT.liftYZ_ps2Y
#print axioms IUT.ps3Comp3_ps3X
#print axioms IUT.ps3Comp3_ps3Y
#print axioms IUT.ps3Comp3_ps3Z
#print axioms IUT.ps23Comp_pad3
#print axioms IUT.quint_reorder
#print axioms IUT.ps3Comp3_comp23
#print axioms IUT.assocL_equation
#print axioms IUT.assocR_equation
#print axioms IUT.assocL_is_lt3
#print axioms IUT.assocR_is_lt3
#print axioms IUT.lt_formal_group_assoc
#print axioms IUT.lt2Sol_assoc
#print axioms IUT.psPowPow_low
#print axioms IUT.ps21Comp_pad
#print axioms IUT.ps21Comp_zero_coeff
#print axioms IUT.ps21Comp_lin
#print axioms IUT.psFam_congr
#print axioms IUT.psFam_mul_right
#print axioms IUT.psFam_mul_left
#print axioms IUT.psSmul_rsum
#print axioms IUT.psMul_congr_le
#print axioms IUT.psPowPow_mul
#print axioms IUT.psSmul_mul_smul
#print axioms IUT.ps21Comp_eq_fam
#print axioms IUT.ps21Comp_mul
#print axioms IUT.ps21Comp_one
#print axioms IUT.ps21Comp_pow
#print axioms IUT.ps21Comp_comp1
#print axioms IUT.ps21Comp_comp2
#print axioms IUT.ps21Comp_inX
#print axioms IUT.ps21Comp_inY
#print axioms IUT.psComp_mul
#print axioms IUT.psComp_pow
#print axioms IUT.psComp_assoc
#print axioms IUT.ltIter_coeff_zero
#print axioms IUT.ltIter_coeff_one
#print axioms IUT.ltIter_comm
#print axioms IUT.psComp_single_one
#print axioms IUT.psComp_mono
#print axioms IUT.psComp_ltPoly_left
#print axioms IUT.ltIter_eq_ltSol
#print axioms IUT.psComp_ps21Comp
#print axioms IUT.zero_lt_equation
#print axioms IUT.ltInv_zero
#print axioms IUT.ltInv_one
#print axioms IUT.lt_formal_group_inverse
#print axioms IUT.lt_formal_group_has_inverse
#print axioms IUT.ltSol_comm
#print axioms IUT.ltSol_zero
#print axioms IUT.ltSol_one
#print axioms IUT.lt_module_add
#print axioms IUT.lt_module_mul
#print axioms IUT.lt_module_add_neg
#print axioms IUT.ltInv_eq_ltSol_neg_one
#print axioms IUT.lt_formal_group_inverse_left
#print axioms IUT.lt_formal_group_inverse_both
#print axioms IUT.ltOModule
#print axioms IUT.ltSol_injective
#print axioms IUT.oModule_bracket_unique
#print axioms IUT.oModule_unique
#print axioms IUT.ltOModule_inverse
#print axioms IUT.rsum_split
#print axioms IUT.int_ipow_p_dvd
#print axioms IUT.zmod_rpow_quot
#print axioms IUT.proj_rpow_p_zero
#print axioms IUT.zpEvalSeg_stable
#print axioms IUT.zpEval
#print axioms IUT.zpEval_zero
#print axioms IUT.zpEval_const
#print axioms IUT.zpEval_X
#print axioms IUT.zpEval_add
#print axioms IUT.proj_rpow_x_zero
#print axioms IUT.zpEval_mul
#print axioms IUT.zpEval_pow
#print axioms IUT.zpEvalSeg_comp
#print axioms IUT.zpEval_comp
#print axioms IUT.zpEval_witness_irrel
#print axioms IUT.ps_eq_X_mul_shift
#print axioms IUT.zpEval_smul
#print axioms IUT.zpEval_neg
#print axioms IUT.proj_rpow_x_low
#print axioms IUT.zpEval_mono
#print axioms IUT.zpEval_single_one
#print axioms IUT.zpEval_ltPoly
#print axioms IUT.zpEval_closed
#print axioms IUT.zpEval_comp_closed
#print axioms IUT.zpEval2Seg_stable
#print axioms IUT.zpEval2
#print axioms IUT.zpEval2_witness_irrel
#print axioms IUT.zpEval2_congr_points
#print axioms IUT.zpEvalSeg_ps21Comp
#print axioms IUT.zpEval_ps21Comp
#print axioms IUT.zpEval_at_zero
#print axioms IUT.zpEval_eq_at_zero
#print axioms IUT.zpEval_ltIter_succ
#print axioms IUT.zero_is_torsion
#print axioms IUT.torsion_zero_iff
#print axioms IUT.torsion_mono
#print axioms IUT.torsion_le
#print axioms IUT.lt2Sol_comp_X_zero
#print axioms IUT.lt_point_unit
#print axioms IUT.lt_point_comm
#print axioms IUT.lt_point_inverse
#print axioms IUT.lt_point_module_add
#print axioms IUT.ltIter_one
#print axioms IUT.lt_point_factor
#print axioms IUT.cofactor_decomp
#print axioms IUT.one_add_p_mul_unit
#print axioms IUT.one_add_p_mul_regular
#print axioms IUT.torsion_one_trivial
#print axioms IUT.torsion_trivial
#print axioms IUT.zpEval3Seg_stable
#print axioms IUT.zpEval3
#print axioms IUT.zpEval3_witness_irrel
#print axioms IUT.zpEval2Seg_one
#print axioms IUT.zpEval3_liftXY
#print axioms IUT.zpEval3_ps3Z
#print axioms IUT.proj_rpow_point_low
#print axioms IUT.rpow_pair_mul
#print axioms IUT.zpEval2_mul
#print axioms IUT.zpEval2_one
#print axioms IUT.zpEval2_pow
#print axioms IUT.eisRing
#print axioms IUT.eisOf
#print axioms IUT.eis_rpow_mk
#print axioms IUT.eis_lambda_pow
#print axioms IUT.eis_one_ne_zero
#print axioms IUT.eisOf_lambda_torsion_shape
#print axioms IUT.eisF_zero
#print axioms IUT.eisF_lambda
#print axioms IUT.lambda_all_torsion
#print axioms IUT.eis_lambda_ne_zero
#print axioms IUT.eisOf_compat_f
#print axioms IUT.eisIter_compat
#print axioms IUT.zpEval2Seg_rsum
#print axioms IUT.nilpotent_cauchy_mul
#print axioms IUT.zpEval3_mul
#print axioms IUT.zpEval3_one
#print axioms IUT.zpEval3_pow
#print axioms IUT.zpPow_eq_rpow
#print axioms IUT.eisF_semilinear
#print axioms IUT.conj_is_torsion
#print axioms IUT.conj_ne_zero
#print axioms IUT.conj_distinct
#print axioms IUT.teich_conj_torsion
#print axioms IUT.teich_conj_ne_zero
#print axioms IUT.teich_conj_distinct
#print axioms IUT.lambda_one_torsion_family
#print axioms IUT.lambda_one_family_distinct
#print axioms IUT.ramifiedEntrance
#print axioms IUT.ramified_entrance_exists
#print axioms IUT.zpEval3_liftYZ
#print axioms IUT.zpEval2_ps2X
#print axioms IUT.zpEval3_ps3X
#print axioms IUT.zpEval2_closed'
#print axioms IUT.proj_xyz_pow_low
#print axioms IUT.proj_Seg3_powpow_high
#print axioms IUT.zpEval3Seg_ps23Comp
#print axioms IUT.zpEval3_ps23Comp
#print axioms IUT.lt_point_assoc
#print axioms IUT.psScale_mul
#print axioms IUT.psScale_eisPoly
#print axioms IUT.eisAut
#print axioms IUT.eisAut_const
#print axioms IUT.eisAut_lambda
#print axioms IUT.eisAut_comp
#print axioms IUT.eisAut_one
#print axioms IUT.eisGal_mul
#print axioms IUT.eisGal_distinct
#print axioms IUT.eisAut_eisF
#print axioms IUT.wsum_supported
#print axioms IUT.lMul_coeff_window
#print axioms IUT.lAdd_coeff_assoc
#print axioms IUT.lAdd_coeff_neg
#print axioms IUT.lMul_coeff_distrib
#print axioms IUT.lMul_coeff_comm
#print axioms IUT.wsum_shift
#print axioms IUT.lMul_coeff_assoc
#print axioms IUT.lMul_coeff_one
#print axioms IUT.laurentRing
#print axioms IUT.laurentOf
#print axioms IUT.eisGal_residue
#print axioms IUT.recRam_mul
#print axioms IUT.eisGal_principal_trivial
#print axioms IUT.eisGal_faithful
#print axioms IUT.recRamLevelOne
#print axioms IUT.recRam_exists
#print axioms IUT.recRam_fixes_base
#print axioms IUT.isgn_succ
#print axioms IUT.tri_bound
#print axioms IUT.theta
#print axioms IUT.theta_zero_coeff
#print axioms IUT.uMon_mul_coeff
#print axioms IUT.uMon_mul_uMon
#print axioms IUT.laurent_uMon_mul
#print axioms IUT.uShift_add
#print axioms IUT.laurent_uMon_unit
#print axioms IUT.tri_step
#print axioms IUT.tri_le
#print axioms IUT.theta_funeq_coeff
#print axioms IUT.theta_funeq
#print axioms IUT.eisIter_succ_comm
#print axioms IUT.eisIter_add
#print axioms IUT.eisTorsion_zero
#print axioms IUT.eisTorsion_mono
#print axioms IUT.eisTorsion_lambda
#print axioms IUT.eisTorsion_step
#print axioms IUT.eisAut_eisIter
#print axioms IUT.eisAut_preserves_torsion
#print axioms IUT.eisIter_semilinear
#print axioms IUT.eisTorsion_conj_scale
#print axioms IUT.eisTorsionTower
#print axioms IUT.eisTorsionTower_exists
#print axioms IUT.eisTorsion_galois_orbit
#print axioms IUT.negPow_neg
#print axioms IUT.tCoeff_one
#print axioms IUT.tCoeff_eq
#print axioms IUT.gauss_bridge
#print axioms IUT.tCoeff_shift
#print axioms IUT.thetaIter_succ
#print axioms IUT.thetaIter_even
#print axioms IUT.thetaIter_odd
#print axioms IUT.negPow_isgn
#print axioms IUT.theta_gauss
#print axioms IUT.eisF_factor
#print axioms IUT.eisTorsion_one_classify
#print axioms IUT.lambda_eis_equation
#print axioms IUT.conj_eis_equation
#print axioms IUT.eisUpper
#print axioms IUT.eisUpper_exists
#print axioms IUT.Grp.pow_add
#print axioms IUT.Grp.mul_inv_rev
#print axioms IUT.Grp.central_pow
#print axioms IUT.tateRel_trans
#print axioms IUT.tateRel_mul
#print axioms IUT.tateRel_inv
#print axioms IUT.tateGrp
#print axioms IUT.tate_exact
#print axioms IUT.tate_q_one
#print axioms IUT.tate_ker
#print axioms IUT.tate_shift_trivial
#print axioms IUT.tate_deck_collapse
#print axioms IUT.tri_nat
#print axioms IUT.tri_int
#print axioms IUT.theta_gauss_tri
#print axioms IUT.theta_pow_one
#print axioms IUT.thetaSection_mul
#print axioms IUT.tri_cocycle
#print axioms IUT.theta_section_rigid
#print axioms IUT.monoThetaWitness
#print axioms IUT.mono_theta_exists
#print axioms IUT.neZeroAt_mono
#print axioms IUT.zpValDecompose
#print axioms IUT.neZeroAt_one_mul
#print axioms IUT.zp_mul_ne_zero
#print axioms IUT.zp_ne_zero_mul
#print axioms IUT.zpDomainData
#print axioms IUT.zpDomain_nonempty
#print axioms IUT.cube_expand
#print axioms IUT.ssq_closed
#print axioms IUT.stri_closed
#print axioms IUT.sq_exponent
#print axioms IUT.ssq_stri
#print axioms IUT.cube_le_ssq
#print axioms IUT.gaussianVolume
#print axioms IUT.gaussian_volume_exists
#print axioms IUT.zres
#print axioms IUT.res1_unit_not_dvd
#print axioms IUT.res1_mul_congr
#print axioms IUT.recInertia_mul
#print axioms IUT.recInertia_principal
#print axioms IUT.recInertia_lambda
#print axioms IUT.recLevelOne_mul_unram
#print axioms IUT.recLevelOne_mul_ram
#print axioms IUT.recLevelOne_ker
#print axioms IUT.recGluing
#print axioms IUT.recGluing_exists
#print axioms IUT.eisCoeff
#print axioms IUT.eisNeZeroAt_ne_zero
#print axioms IUT.eisOf_injective
#print axioms IUT.eisNeZeroAt_lambda_mul
#print axioms IUT.eis_lambda_mul_ne_zero
#print axioms IUT.eis_lambda_division
#print axioms IUT.eis_residue_mul
#print axioms IUT.eis_unit_mul_ne_zero
#print axioms IUT.eisDomainData
#print axioms IUT.eisDomain_nonempty
#print axioms IUT.endo_eisF_comm
#print axioms IUT.endo_eisIter_comm
#print axioms IUT.endo_preserves_torsion
#print axioms IUT.endo_lambda_torsion
#print axioms IUT.endo_lambda_classify
#print axioms IUT.endo_lambda_root
#print axioms IUT.eisEndoRigidity
#print axioms IUT.eisEndoRigidity_exists
#print axioms IUT.geom_factor
#print axioms IUT.qCoeff_peel
#print axioms IUT.lin_div
#print axioms IUT.pEval_div
#print axioms IUT.pEval_root_factor
#print axioms IUT.roots_bound
#print axioms IUT.pEval_bin
#print axioms IUT.bin_roots_bound
#print axioms IUT.eis_roots_bound
#print axioms IUT.nsum_congr
#print axioms IUT.nsum_mul_right
#print axioms IUT.efSum
#print axioms IUT.inertExt_sum
#print axioms IUT.splitExt_sum
#print axioms IUT.ramifiedExt_sum
#print axioms IUT.semiLocalFrobenioid
#print axioms IUT.decompPullback
#print axioms IUT.normDeg_add
#print axioms IUT.normDeg_frob
#print axioms IUT.normDeg_linear
#print axioms IUT.efg_identity
#print axioms IUT.efg_deg
#print axioms IUT.efg_pullback
#print axioms IUT.inert_efg
#print axioms IUT.split_efg
#print axioms IUT.ramified_efg
#print axioms IUT.normFunctor
#print axioms IUT.norm_pullback_obj
#print axioms IUT.norm_pullback_hom_d
#print axioms IUT.norm_pullback_hom_c
#print axioms IUT.semiLocal_iso_objects_eq
#print axioms IUT.semiLocalFrobenioid_gaunt
#print axioms IUT.semiLocal_iso_unique
#print axioms IUT.semiLocal_rigid
#print axioms IUT.nnqAdd_assoc
#print axioms IUT.nnqAdd_comm
#print axioms IUT.nnqOfNat_add
#print axioms IUT.nnq_div_cancel
#print axioms IUT.radd_assoc
#print axioms IUT.realify_add
#print axioms IUT.realify_frob
#print axioms IUT.degR_add
#print axioms IUT.degR_frob
#print axioms IUT.degR_realify
#print axioms IUT.rdiv_divisible
#print axioms IUT.qdiv_not_divisible
#print axioms IUT.realification_gains_divisibility
#print axioms IUT.realFrobenioid
#print axioms IUT.real_pilot_division
#print axioms IUT.realifyFunctor
#print axioms IUT.real_iso_objects_eq
#print axioms IUT.real_gaunt_isoUnique
#print axioms IUT.archFrobenioid
#print axioms IUT.arch_divisible
#print axioms IUT.arch_pilot_division
#print axioms IUT.nonarch_pilot_obstruction
#print axioms IUT.arch_vs_nonarch
#print axioms IUT.localArchFunctor
#print axioms IUT.local_realification_gains_divisibility
#print axioms IUT.mixedAdd_assoc
#print axioms IUT.mixedFrob_add
#print axioms IUT.mixedFrob_frob
#print axioms IUT.degMixed_add
#print axioms IUT.degMixed_frob
#print axioms IUT.mixedFrobenioid
#print axioms IUT.mixed_iso_objects_eq
#print axioms IUT.mixed_gaunt_isoUnique
#print axioms IUT.mixed_divisibility_dichotomy
#print axioms IUT.mixed_pilot_division
#print axioms IUT.mixed_fin_zero_divisible
#print axioms IUT.mixed_single_not_divisible
EOF
lake env lean /tmp/iut_check_axioms.lean

echo "OK: all theorems verified, no sorry."
echo "Expected: standard axioms only. mono_implies_bi is axiom-free;"
echo "bi_implies_mono_classical requires Classical.choice (the point of M1-2)."
