#!/usr/bin/env bash
# IUT 系3.12 形式検証のビルド + 公理チェック
# 必要: elan (https://github.com/leanprover/elan)
set -euo pipefail
cd "$(dirname "$0")"

lake build

# sorry や追加公理に依存していないことを確認
cat > /tmp/iut_check_axioms.lean <<'EOF'
import IUT
#print axioms IUT.verdict
#print axioms IUT.ss_incompatible
#print axioms IUT.cor312_independent
#print axioms IUT.controversy_reduces_to_rc
#print axioms IUT.mono_implies_bi
#print axioms IUT.bi_implies_mono_classical
#print axioms IUT.AddSym.act_comp
#print axioms IUT.theta_labels
#print axioms IUT.path_col
#print axioms IUT.cross_col_needs_theta
#print axioms IUT.abc_implies_asymptotic_fermat
#print axioms IUT.szpiro_of_cor312
#print axioms IUT.szpiro_of_cor312_precise
#print axioms IUT.cor312_of_multiradial
#print axioms IUT.strict_evaluation_obstruction
#print axioms IUT.padding_necessary
#print axioms IUT.multiradial_consistent
#print axioms IUT.gaussian_obstruction
#print axioms IUT.szpiro_of_multiradial
#print axioms IUT.recon_log_compat
#print axioms IUT.addSym_inverse
#print axioms IUT.bicoric_constant
#print axioms IUT.theta_value_pm_symmetry
#print axioms IUT.two_mul_procTotal
#print axioms IUT.height_bounded_of_uniform_szpiro
#print axioms IUT.abc_bounds_catalan23
#print axioms IUT.six_mul_sumSq
#print axioms IUT.invariant_transport
#print axioms IUT.geometric_normal
#print axioms IUT.outer_conjugation_unique
#print axioms IUT.outer_action_inner_on_kernel
#print axioms IUT.slim_faithful
#print axioms IUT.section_decomposition
#print axioms IUT.theta_deck_not_finite
#print axioms IUT.theta_exponent_unique
#print axioms IUT.theta_exponent_not_periodic
#print axioms IUT.finite_quotient_collapses_theta
#print axioms IUT.arithmetic_quotient_collapses_theta
#print axioms IUT.temperedArithmetic_consistent
#print axioms IUT.tempered_invariant_transport
#print axioms IUT.findWitness_spec
#print axioms IUT.abelianization_determines
#print axioms IUT.reconCore_correct
#print axioms IUT.padic_recon_monoanabelian
#print axioms IUT.padic_recon_bianabelian
#print axioms IUT.padic_invariant_transport
#print axioms IUT.cyclotome_indeterminacy
#print axioms IUT.marked_cyclotome_rigid
#print axioms IUT.theta_comm
#print axioms IUT.mono_theta_cyclotomic_rigidity
#print axioms IUT.rigid_theta_values
#print axioms IUT.Frobenioid.deg_zero
#print axioms IUT.frob_not_invertible
#print axioms IUT.gaussianDiv_deg
#print axioms IUT.frobenioid_realizes_qpilot
#print axioms IUT.degree_volume_consistent
#print axioms IUT.GrpCong.inv_compat
#print axioms IUT.quot_exact
#print axioms IUT.quot_universal
#print axioms IUT.limit_universal
#print axioms IUT.toZhat_injective
#print axioms IUT.zmod_bounded_exponent
#print axioms IUT.zmod_collapses_theta
#print axioms IUT.equivariant_is_right_mul
#print axioms IUT.fiber_functor_recovers_group
#print axioms IUT.level_transition_equivariant
#print axioms IUT.galois_closure
#print axioms IUT.genOpen_minimal
#print axioms IUT.continuous_into_gen
#print axioms IUT.limitProj_continuous
#print axioms IUT.limit_mul_continuous
#print axioms IUT.limit_inv_continuous
#print axioms IUT.projKernel_isOpen
#print axioms IUT.cylinder_nbhd_basis
#print axioms IUT.projKernel_nbhd
#print axioms IUT.zhat_proj_surjective
#print axioms IUT.cosetAction
#print axioms IUT.orbit_stabilizer
#print axioms IUT.orbit_transitive
#print axioms IUT.every_orbit_is_coset
#print axioms IUT.coset_hom_iff
#print axioms IUT.levelAction_smooth
#print axioms IUT.levelAction_stabilizer_open
#print axioms IUT.pigeonhole
#print axioms IUT.card_unique
#print axioms IUT.finite_bounded_exponent
#print axioms IUT.zmod_finite
#print axioms IUT.zmod_listable
#print axioms IUT.listable_discrete_compact
#print axioms IUT.zmod_compact
#print axioms IUT.compact_image
#print axioms IUT.compact_prod
#print axioms IUT.restrictEquiv
#print axioms IUT.skel_classification
#print axioms IUT.fiberAut
#print axioms IUT.from_to
#print axioms IUT.to_from
#print axioms IUT.sga1Equivalence
#print axioms IUT.gsets_G1_final
#print axioms IUT.gsets_G1_pullback
#print axioms IUT.gsets_G2_initial
#print axioms IUT.gsets_G2_sum
#print axioms IUT.gsets_G3_factorization
#print axioms IUT.gsets_G4_forgetful_preserves_pullback
#print axioms IUT.gsets_G5_forgetful_preserves_sum
#print axioms IUT.gsets_G6_reflects_iso
#print axioms IUT.GaloisCatData.eq_mono
#print axioms IUT.GaloisCatData.feq_surj
#print axioms IUT.GaloisCatData.fiber_faithful
#print axioms IUT.GaloisCatData.mono_of_fiber_injective
#print axioms IUT.GaloisCatData.evaluation_injective
#print axioms IUT.GaloisCatData.galois_evaluation_bijective
#print axioms IUT.gsetGaloisData
#print axioms IUT.galoisCatData_consistent
#print axioms IUT.CatIso.ext
#print axioms IUT.GaloisCatData.autGrp
#print axioms IUT.GaloisCatData.homFunctor
#print axioms IUT.GaloisCatData.homFunctor_faithful
#print axioms IUT.GaloisCatData.connected_hom_surjective
#print axioms IUT.GaloisCatData.split_connected_transitive
#print axioms IUT.DescentData.homFunctor_full
#print axioms IUT.DescentData.sga1_fully_faithful
#print axioms IUT.gsetDescentData
#print axioms IUT.descentData_consistent
#print axioms IUT.Grp.mul_inv_cancel_left
#print axioms IUT.QuotientData.quotient_realizes_coset
#print axioms IUT.QuotientData.sga1_essentially_surjective
#print axioms IUT.gsetQuotientData
#print axioms IUT.quotientData_consistent
#print axioms IUT.GaloisCatData.aut_transition_exists_unique
#print axioms IUT.GaloisCatData.aut_transition_surjective
#print axioms IUT.GaloisTower.transAut_mul
#print axioms IUT.GaloisTower.towerSystem
#print axioms IUT.GaloisTower.pi1Tower
#print axioms IUT.GaloisTower.pi1Tower_mul_continuous
#print axioms IUT.unitAction_galois
#print axioms IUT.galoisTower_consistent
#print axioms IUT.assemble_level
#print axioms IUT.refine_step
#print axioms IUT.natSystem_compact
#print axioms IUT.pi1Tower_compact
#print axioms IUT.factChain_compact
#print axioms IUT.SumData.connected_factors
#print axioms IUT.SumData.hom_sum_realizes
#print axioms IUT.SumData.sum_decomposition
#print axioms IUT.gsetSumData
#print axioms IUT.sumData_consistent
#print axioms IUT.Zp
#print axioms IUT.Zp_compact
#print axioms IUT.Zp_mul_continuous
#print axioms IUT.toZp_injective
#print axioms IUT.unramifiedRec
#print axioms IUT.unramifiedRec_kernel
#print axioms IUT.unramifiedRec_level_surj
#print axioms IUT.unramifiedLocalCFT
#print axioms IUT.localCFT_consistent
#print axioms IUT.map_le_iff_le_comap
#print axioms IUT.comap_map_of_injective
#print axioms IUT.norm_correspondence
#print axioms IUT.unramified_norm_correspondence
#print axioms IUT.dvd_sub_mul
#print axioms IUT.zpMul
#print axioms IUT.zpMul_comm
#print axioms IUT.geom_identity
#print axioms IUT.zmod_principal_unit_invertible
#print axioms IUT.dvd_sub_geomSum
#print axioms IUT.geomSum_levels
#print axioms IUT.isPrincipalUnit_mul
#print axioms IUT.zpGeomInv
#print axioms IUT.principalUnits
#print axioms IUT.principalUnits_comm
#print axioms IUT.principal_unit_invertible
#print axioms IUT.toZp_one_add_principal
#print axioms IUT.unitFiltration
#print axioms IUT.unitFiltration_full
#print axioms IUT.unitFiltration_antitone
#print axioms IUT.unitFiltration_separated
#print axioms IUT.levelTheta
#print axioms IUT.unitTheta_hom
#print axioms IUT.unitTheta_kernel
#print axioms IUT.unitTheta_surj
#print axioms IUT.succ_mul_chs
#print axioms IUT.bezout
#print axioms IUT.euclid
#print axioms IUT.isPrime_two
#print axioms IUT.isPrime_three
#print axioms IUT.prime_dvd_chs
#print axioms IUT.binomial
#print axioms IUT.freshman
#print axioms IUT.fermat_little
#print axioms IUT.pow_sub_factor
#print axioms IUT.pow_lift
#print axioms IUT.teich_step
#print axioms IUT.teich
#print axioms IUT.teich_reduction
#print axioms IUT.teich_mul
#print axioms IUT.teich_one
#print axioms IUT.teich_frobenius
#print axioms IUT.zpPow
#print axioms IUT.zpPow_succ
#print axioms IUT.euclid_int
#print axioms IUT.flt_unit
#print axioms IUT.euler_pow
#print axioms IUT.teich_root_of_unity
#print axioms IUT.teich_invertible
#print axioms IUT.zpMul_assoc
#print axioms IUT.zpOne_mul
#print axioms IUT.isPrincipalUnit_of_level_one
#print axioms IUT.teich_congr
#print axioms IUT.unit_decomposition
#print axioms IUT.decomposition_unique
#print axioms IUT.not_dvd_ipow
#print axioms IUT.isZpUnit_mul
#print axioms IUT.isZpUnit_teich
#print axioms IUT.isZpUnit_of_principal
#print axioms IUT.unit_pow_principal
#print axioms IUT.zpUnitInv_mul
#print axioms IUT.zpUnits
#print axioms IUT.zpUnits_comm
#print axioms IUT.zpUnits_decomposition
#print axioms IUT.prodHom_injective
#print axioms IUT.recQp
#print axioms IUT.recQp_injective
#print axioms IUT.recQp_units_to_inertia
#print axioms IUT.fullLocalCFT
#print axioms IUT.fullLocalCFT_consistent
#print axioms IUT.CRing.right_distrib
#print axioms IUT.CRing.mul_zero
#print axioms IUT.CRing.toGrp
#print axioms IUT.intRing
#print axioms IUT.zmodRing
#print axioms IUT.zpRing
#print axioms IUT.toZpRing
#print axioms IUT.projRing
#print axioms IUT.rsum_add
#print axioms IUT.rsum_reflect
#print axioms IUT.rsum_triangle
#print axioms IUT.psRing
#print axioms IUT.psConstHom
#print axioms IUT.rsum_single
#print axioms IUT.psPow_add
#print axioms IUT.psPow_coeff_zero
#print axioms IUT.psComp_add
#print axioms IUT.psComp_one
#print axioms IUT.psComp_X
#print axioms IUT.psComp_coeff_zero
#print axioms IUT.psComp_coeff_one
#print axioms IUT.CRing.add_quad_swap
#print axioms IUT.psPow_congr
#print axioms IUT.psPow_coeff_diag
#print axioms IUT.psPow_coeff_congr
#print axioms IUT.lubin_tate_unique
#print axioms IUT.CRing.cancel_to_annihilate
#print axioms IUT.zp_p_regular
#print axioms IUT.zp_unit_regular
#print axioms IUT.zp_lt_cancel
#print axioms IUT.lubin_tate_unique_zp
#print axioms IUT.zpDivP
#print axioms IUT.zpDivP_mul_cancel
#print axioms IUT.zpDivP_cancel
#print axioms IUT.zp_dvd_p_iff
#print axioms IUT.zp_flt
#print axioms IUT.zp_frobenius_divisible
#print axioms IUT.rofNat_add
#print axioms IUT.rofNat_mul
#print axioms IUT.binomial2
#print axioms IUT.rofNat_chs_factor
#print axioms IUT.freshman_ring
#print axioms IUT.freshman_ps
#print axioms IUT.psC_mul_coeff
#print axioms IUT.rofNat_zp
#print axioms IUT.freshman_zp
#print axioms IUT.ringHom_rsum
#print axioms IUT.psMap_mul
#print axioms IUT.psMap_comp
#print axioms IUT.psMono_mul
#print axioms IUT.psMono_pow
#print axioms IUT.psComp_mono_coeff
#print axioms IUT.psComp_mono_coeff_zero
#print axioms IUT.zmod_flt
#print axioms IUT.freshman_exact
#print axioms IUT.psSingle_pow
#print axioms IUT.psComp_single
#print axioms IUT.frobenius_trunc
#print axioms IUT.frobenius_charp
#print axioms IUT.ltPoly_coeff_zero
#print axioms IUT.ltPoly_coeff_one
#print axioms IUT.ltPoly_reduction
#print axioms IUT.ltError_reduction
#print axioms IUT.ltError_divisible
#print axioms IUT.ltSol
#print axioms IUT.ltSeg_eq_sol
#print axioms IUT.ltSol_div
#print axioms IUT.ltSol_equation
#print axioms IUT.lubin_tate_exists
#print axioms IUT.lubin_tate
#print axioms IUT.elementaryFrobenioid
#print axioms IUT.degFunctor
#print axioms IUT.frobFunctor
#print axioms IUT.frob_no_right_inverse
#print axioms IUT.iso_deg_one
#print axioms IUT.iso_objects_eq
#print axioms IUT.hom_exists_but_no_iso
#print axioms IUT.degMor
#print axioms IUT.frobFunctor_matches_frob
#print axioms IUT.deg_frobFunctor
#print axioms IUT.rsum_psRing_coeff
#print axioms IUT.ps2Pow_tcoeff_zero
#print axioms IUT.ps2Comp1_add
#print axioms IUT.ps2Comp1_one
#print axioms IUT.ps2Comp1_X
#print axioms IUT.ps2Lin_00
#print axioms IUT.ps2Lin_10
#print axioms IUT.ps2Lin_01
#print axioms IUT.psPow_psC
#print axioms IUT.ps2X_pow
#print axioms IUT.ps2Y_pow
#print axioms IUT.ps2MonoXY
#print axioms IUT.ps2Comp2_coords
#print axioms IUT.ps2Comp1_coordX
#print axioms IUT.ps2Comp1_coordY
#print axioms IUT.psMap_constHom_psX
#print axioms IUT.fgl_equation_identity
#print axioms IUT.inX_ltPoly_00
#print axioms IUT.inY_ltPoly_00
#print axioms IUT.degZ_add
#print axioms IUT.degZ_frob
#print axioms IUT.rationalFrobenioid
#print axioms IUT.rational_frob_not_invertible
#print axioms IUT.rational_gaussian_deg
#print axioms IUT.rationalDegVol
#print axioms IUT.rational_qpilot_volume
#print axioms IUT.degZ_single_valuation
#print axioms IUT.divisorFrobenioid
#print axioms IUT.divDegFunctor
#print axioms IUT.divisor_iso_objects_eq
#print axioms IUT.divisor_iso_deg_eq
#print axioms IUT.divisor_hom_exists_but_no_iso
#print axioms IUT.psRingHom
#print axioms IUT.ps2Map_X
#print axioms IUT.ps2Map_Y
#print axioms IUT.ps2Map_comp1
#print axioms IUT.ps2Map_comp2
#print axioms IUT.ps2Map_psC
#print axioms IUT.ps2Map_inY
#print axioms IUT.ps2Map_equation
#print axioms IUT.ltFormalGroup_reduction
#print axioms IUT.ltFormalGroup_reduction_linear
#print axioms IUT.isoUnique_subsingleton
#print axioms IUT.divisorFrobenioid_gaunt
#print axioms IUT.divisor_iso_is_id
#print axioms IUT.divisorFrobenioid_iso_unique
#print axioms IUT.divisorFrobenioid_rigid
#print axioms IUT.elementaryFrobenioid_gaunt
#print axioms IUT.elementary_iso_unique
#print axioms IUT.deloop_every_hom_iso
#print axioms IUT.deloop_aut_torsor
#print axioms IUT.deloop_gaunt
#print axioms IUT.deloop_not_iso_unique
#print axioms IUT.gaunt_dichotomy
#print axioms IUT.deloop_intGrp_not_iso_unique
#print axioms IUT.deloopInd_nontrivial
#print axioms IUT.freshman_exact_ring
#print axioms IUT.frobHom
#print axioms IUT.freshman_exact_gen
#print axioms IUT.psMap_trunc
#print axioms IUT.frobenius_trunc_gen
#print axioms IUT.frobenius_charp_gen
#print axioms IUT.frobenius_gen_recovers
#print axioms IUT.psRing_char
#print axioms IUT.ps2Comp1_mono
#print axioms IUT.ps2_powXY
#print axioms IUT.ps2Comp2_powXY_hit
#print axioms IUT.ps2Comp2_powXY_missY
#print axioms IUT.ps2Comp2_powXY_missX
#print axioms IUT.ps2Pow_frob_hit
#print axioms IUT.ps2Pow_frob_missY
#print axioms IUT.ps2Pow_frob_missX
#print axioms IUT.frobenius2_charp
#print axioms IUT.lt_error_vanishes_modp
#print axioms IUT.lt_error_vanishes_modp'
#print axioms IUT.lt2Err_zero_iff_equation
#print axioms IUT.ps2Map_zero_cond
#print axioms IUT.lt2Err_reduction
#print axioms IUT.lt2Err_divisible
#print axioms IUT.lt2Div
#print axioms IUT.lt2Div_cancel
#print axioms IUT.gpow_add
#print axioms IUT.gpow_mul
#print axioms IUT.gpow_mul_dist
#print axioms IUT.splitFrobenioid
#print axioms IUT.splitForget
#print axioms IUT.unit_endo_comp
#print axioms IUT.splitForget_unit
#print axioms IUT.split_iso_objects_eq
#print axioms IUT.splitFrobenioid_gaunt
#print axioms IUT.split_iso_unit_arbitrary
#print axioms IUT.split_polyiso_torsor
#print axioms IUT.split_not_iso_unique
#print axioms IUT.split_forget_mapIso_eq
#print axioms IUT.split_dichotomy_refined
#print axioms IUT.splitInd_nontrivial
#print axioms IUT.ps2Mul_coeff
#print axioms IUT.ps2Pow_one
#print axioms IUT.ps2Mul_coeff_congr
#print axioms IUT.ps2Pow_coeff_congr
#print axioms IUT.ps2Pow_coeff_congr'
#print axioms IUT.ps2Comp1_single_one
#print axioms IUT.lt2_lhs_decomp
#print axioms IUT.inX_mul_inY
#print axioms IUT.lt2_rhs_coeff
#print axioms IUT.discCat
#print axioms IUT.localFrobenioid
#print axioms IUT.localToElementary
#print axioms IUT.fiberedFrobenioid
#print axioms IUT.fibProj
#print axioms IUT.fibProj_endo_id
#print axioms IUT.no_cross_prime_hom
#print axioms IUT.fiberIncl
#print axioms IUT.fiber_local_iso
#print axioms IUT.divRestrictFunctor
#print axioms IUT.restrict_determines
#print axioms IUT.fibered_iso_objects_eq
#print axioms IUT.fiberedFrobenioid_gaunt
#print axioms IUT.fibered_iso_unique
#print axioms IUT.fibered_rigid
#print axioms IUT.rsum_single_diff
#print axioms IUT.ltPow_low
#print axioms IUT.ltPow_diag
#print axioms IUT.lt2_rhs_split
#print axioms IUT.rpow_add
#print axioms IUT.lt2Sol
#print axioms IUT.lt2Seg_stable
#print axioms IUT.lt2Seg_eq_sol
#print axioms IUT.lt2Seg_high
#print axioms IUT.lt2Sol_div
#print axioms IUT.lt2Sol_equation
#print axioms IUT.lt2Sol_is_formal_group
#print axioms IUT.lt_formal_group_exists
#print axioms IUT.splitFiberedFrobenioid
#print axioms IUT.sfForgetUnit
#print axioms IUT.sfProj
#print axioms IUT.sfProj_onHom_factor
#print axioms IUT.localSplitFrobenioid
#print axioms IUT.sfFiberIncl
#print axioms IUT.sf_fiber_local_iso
#print axioms IUT.sf_iso_objects_eq
#print axioms IUT.splitFiberedFrobenioid_gaunt
#print axioms IUT.sf_polyiso_torsor
#print axioms IUT.sf_forget_mapIso_eq
#print axioms IUT.sf_not_iso_unique
#print axioms IUT.sf_dichotomy
#print axioms IUT.lt_formal_group_unique
#print axioms IUT.lt_formal_group_exists_unique
#print axioms IUT.rsum_exchange
#print axioms IUT.swap_mul
#print axioms IUT.swap_pow
#print axioms IUT.swap_comp1
#print axioms IUT.swap_rhs
#print axioms IUT.swap_is_formal_group
#print axioms IUT.lt_formal_group_comm
#print axioms IUT.lt2Sol_comm
#print axioms IUT.towerCat
#print axioms IUT.tower_nontrivial
#print axioms IUT.tower_no_descent
#print axioms IUT.ramifiedFrobenioid
#print axioms IUT.ramProj
#print axioms IUT.ramProj_vertical_id
#print axioms IUT.ramVerticalIncl
#print axioms IUT.ramVerticalIncl_faithful
#print axioms IUT.ramVerticalIncl_full
#print axioms IUT.pullbackFunctor
#print axioms IUT.pullback_deg
#print axioms IUT.ramPullbackMor
#print axioms IUT.ramProj_pullbackMor
#print axioms IUT.ram_hom_factor
#print axioms IUT.pullback_incl_compat
#print axioms IUT.ram_iso_e_one
#print axioms IUT.ram_iso_objects_eq
#print axioms IUT.ramifiedFrobenioid_gaunt
#print axioms IUT.ram_iso_unique
#print axioms IUT.ram_rigid
#print axioms IUT.ram_no_descent
#print axioms IUT.pullback_not_invertible
#print axioms IUT.ramSplitFrobenioid
#print axioms IUT.rsForgetUnit
#print axioms IUT.rsProj
#print axioms IUT.rsProj_onHom_factor
#print axioms IUT.rsPullbackMor
#print axioms IUT.rsProj_pullbackMor
#print axioms IUT.rs_hom_factor
#print axioms IUT.rs_iso_e_one
#print axioms IUT.rs_iso_objects_eq
#print axioms IUT.ramSplitFrobenioid_gaunt
#print axioms IUT.rsUnitIso
#print axioms IUT.rs_polyiso_torsor
#print axioms IUT.rs_forget_mapIso_eq
#print axioms IUT.rs_not_iso_unique
#print axioms IUT.rs_dichotomy
#print axioms IUT.rs_pullback_not_invertible
#print axioms IUT.RingHom.comp
#print axioms IUT.ps3Lin_000
#print axioms IUT.ps3Lin_001
#print axioms IUT.ps3Lin_010
#print axioms IUT.ps3Lin_100
#print axioms IUT.ps3Mul_coeff
#print axioms IUT.ps3Pow_tcoeff_zero
#print axioms IUT.ps3Comp1
#print axioms IUT.in3X_000
#print axioms IUT.in3Y_000
#print axioms IUT.in3Z_000
#print axioms IUT.ps3Comp3
#print axioms IUT.ps3Lin_linear_conditions
#print axioms IUT.ps3Pow_one
#print axioms IUT.ps3Mul_coeff_congr
#print axioms IUT.ps3Pow_coeff_congr
#print axioms IUT.ps3Pow_coeff_congr'
#print axioms IUT.ps3Comp1_add
#print axioms IUT.ps3Comp1_single_one
#print axioms IUT.ps3Comp1_mono
#print axioms IUT.lt3_lhs_decomp
#print axioms IUT.in3X_pow
#print axioms IUT.in3Y_pow
#print axioms IUT.in3Z_pow
#print axioms IUT.in3X_mul_in3Y
#print axioms IUT.ps3_constV_mul_inZ
#print axioms IUT.lt3_rhs_coeff
#print axioms IUT.lt3_rhs_split
#print axioms IUT.lt3_unique
#print axioms IUT.ps23Comp
#print axioms IUT.ps3Mul_deg1_zero
#print axioms IUT.ps23Comp_000
#print axioms IUT.ps23Comp_lin
#print axioms IUT.assocL
#print axioms IUT.assocR
#print axioms IUT.assocL_000
#print axioms IUT.assocR_000
#print axioms IUT.assocL_linear
#print axioms IUT.assocR_linear
#print axioms IUT.ps3Mul_low_zero
#print axioms IUT.ps3PowPow_low
#print axioms IUT.liftXY_mul
#print axioms IUT.liftXY_pow
#print axioms IUT.liftXY_comp1
#print axioms IUT.liftYZ_mul
#print axioms IUT.liftYZ_pow
#print axioms IUT.liftYZ_comp1
#print axioms IUT.ps3X_eq_in3X
#print axioms IUT.ps3Y_eq_in3Y
#print axioms IUT.ps3Z_eq_in3Z
#print axioms IUT.ps3Comp1_in3X
#print axioms IUT.ps3Comp1_in3Y
#print axioms IUT.ps3Comp1_in3Z
#print axioms IUT.rsum_pad
#print axioms IUT.ps3_const_mul
#print axioms IUT.ps3Smul_eq
#print axioms IUT.ps3Fam_congr
#print axioms IUT.ps3Fam_mul_right
#print axioms IUT.ps3Fam_mul_left
#print axioms IUT.ps3Smul_rsum
#print axioms IUT.ps3Mul_congr_le
#print axioms IUT.CRing.mul_mul_comm
#print axioms IUT.ps3PowPow_mul
#print axioms IUT.ps3Const_mul
#print axioms IUT.ps3Smul_mul_smul
#print axioms IUT.ps23Comp_eq_fam
#print axioms IUT.quad_sum_reindex
#print axioms IUT.ps23Comp_mul
#print axioms IUT.ps23Comp_one
#print axioms IUT.ps23Comp_add
#print axioms IUT.ps2Mul_low_zero
#print axioms IUT.ps2PowPow_low
#print axioms IUT.ps23Comp_pow
#print axioms IUT.ps23Comp_comp1
#print axioms IUT.ps2Comp2_pad
#print axioms IUT.ps23Comp_comp2
#print axioms IUT.psX_pow_coeff
#print axioms IUT.psComp_X_right
#print axioms IUT.ps23Comp_inX
#print axioms IUT.ps23Comp_inY
#print axioms IUT.ps3Comp1_ps3X
#print axioms IUT.ps3Comp1_ps3Y
#print axioms IUT.ps3Comp1_ps3Z
#print axioms IUT.ps3TriplePow_low
#print axioms IUT.ps3TriplePow_mul
#print axioms IUT.ps3Comp3_eq_fam
#print axioms IUT.hex_sum_reindex
#print axioms IUT.ps3Comp3_mul
#print axioms IUT.ps3Comp3_one
#print axioms IUT.ps3Comp3_pow
#print axioms IUT.ps3Comp1_X
#print axioms IUT.ps23Comp_X
#print axioms IUT.ps23Comp_Y
#print axioms IUT.ps3Comp3_liftXY
#print axioms IUT.ps3Comp3_liftYZ
#print axioms IUT.liftXY_comp2
#print axioms IUT.liftYZ_comp2
#print axioms IUT.liftYZ_in2X
#print axioms IUT.liftYZ_in2Y
#print axioms IUT.liftYZ_ps2Y
#print axioms IUT.ps3Comp3_ps3X
#print axioms IUT.ps3Comp3_ps3Y
#print axioms IUT.ps3Comp3_ps3Z
#print axioms IUT.ps23Comp_pad3
#print axioms IUT.quint_reorder
#print axioms IUT.ps3Comp3_comp23
#print axioms IUT.assocL_equation
#print axioms IUT.assocR_equation
#print axioms IUT.assocL_is_lt3
#print axioms IUT.assocR_is_lt3
#print axioms IUT.lt_formal_group_assoc
#print axioms IUT.lt2Sol_assoc
#print axioms IUT.psPowPow_low
#print axioms IUT.ps21Comp_pad
#print axioms IUT.ps21Comp_zero_coeff
#print axioms IUT.ps21Comp_lin
#print axioms IUT.psFam_congr
#print axioms IUT.psFam_mul_right
#print axioms IUT.psFam_mul_left
#print axioms IUT.psSmul_rsum
#print axioms IUT.psMul_congr_le
#print axioms IUT.psPowPow_mul
#print axioms IUT.psSmul_mul_smul
#print axioms IUT.ps21Comp_eq_fam
#print axioms IUT.ps21Comp_mul
#print axioms IUT.ps21Comp_one
#print axioms IUT.ps21Comp_pow
#print axioms IUT.ps21Comp_comp1
#print axioms IUT.ps21Comp_comp2
#print axioms IUT.ps21Comp_inX
#print axioms IUT.ps21Comp_inY
#print axioms IUT.psComp_mul
#print axioms IUT.psComp_pow
#print axioms IUT.psComp_assoc
#print axioms IUT.ltIter_coeff_zero
#print axioms IUT.ltIter_coeff_one
#print axioms IUT.ltIter_comm
#print axioms IUT.psComp_single_one
#print axioms IUT.psComp_mono
#print axioms IUT.psComp_ltPoly_left
#print axioms IUT.ltIter_eq_ltSol
#print axioms IUT.psComp_ps21Comp
#print axioms IUT.zero_lt_equation
#print axioms IUT.ltInv_zero
#print axioms IUT.ltInv_one
#print axioms IUT.lt_formal_group_inverse
#print axioms IUT.lt_formal_group_has_inverse
#print axioms IUT.ltSol_comm
#print axioms IUT.ltSol_zero
#print axioms IUT.ltSol_one
#print axioms IUT.lt_module_add
#print axioms IUT.lt_module_mul
#print axioms IUT.lt_module_add_neg
#print axioms IUT.ltInv_eq_ltSol_neg_one
#print axioms IUT.lt_formal_group_inverse_left
#print axioms IUT.lt_formal_group_inverse_both
#print axioms IUT.ltOModule
#print axioms IUT.ltSol_injective
#print axioms IUT.oModule_bracket_unique
#print axioms IUT.oModule_unique
#print axioms IUT.ltOModule_inverse
#print axioms IUT.rsum_split
#print axioms IUT.int_ipow_p_dvd
#print axioms IUT.zmod_rpow_quot
#print axioms IUT.proj_rpow_p_zero
#print axioms IUT.zpEvalSeg_stable
#print axioms IUT.zpEval
#print axioms IUT.zpEval_zero
#print axioms IUT.zpEval_const
#print axioms IUT.zpEval_X
#print axioms IUT.zpEval_add
#print axioms IUT.proj_rpow_x_zero
#print axioms IUT.zpEval_mul
#print axioms IUT.zpEval_pow
#print axioms IUT.zpEvalSeg_comp
#print axioms IUT.zpEval_comp
#print axioms IUT.zpEval_witness_irrel
#print axioms IUT.ps_eq_X_mul_shift
#print axioms IUT.zpEval_smul
#print axioms IUT.zpEval_neg
#print axioms IUT.proj_rpow_x_low
#print axioms IUT.zpEval_mono
#print axioms IUT.zpEval_single_one
#print axioms IUT.zpEval_ltPoly
#print axioms IUT.zpEval_closed
#print axioms IUT.zpEval_comp_closed
#print axioms IUT.zpEval2Seg_stable
#print axioms IUT.zpEval2
#print axioms IUT.zpEval2_witness_irrel
#print axioms IUT.zpEval2_congr_points
#print axioms IUT.zpEvalSeg_ps21Comp
#print axioms IUT.zpEval_ps21Comp
#print axioms IUT.zpEval_at_zero
#print axioms IUT.zpEval_eq_at_zero
#print axioms IUT.zpEval_ltIter_succ
#print axioms IUT.zero_is_torsion
#print axioms IUT.torsion_zero_iff
#print axioms IUT.torsion_mono
#print axioms IUT.torsion_le
#print axioms IUT.lt2Sol_comp_X_zero
#print axioms IUT.lt_point_unit
#print axioms IUT.lt_point_comm
#print axioms IUT.lt_point_inverse
#print axioms IUT.lt_point_module_add
#print axioms IUT.ltIter_one
#print axioms IUT.lt_point_factor
#print axioms IUT.cofactor_decomp
#print axioms IUT.one_add_p_mul_unit
#print axioms IUT.one_add_p_mul_regular
#print axioms IUT.torsion_one_trivial
#print axioms IUT.torsion_trivial
#print axioms IUT.zpEval3Seg_stable
#print axioms IUT.zpEval3
#print axioms IUT.zpEval3_witness_irrel
#print axioms IUT.zpEval2Seg_one
#print axioms IUT.zpEval3_liftXY
#print axioms IUT.zpEval3_ps3Z
#print axioms IUT.proj_rpow_point_low
#print axioms IUT.rpow_pair_mul
#print axioms IUT.zpEval2_mul
#print axioms IUT.zpEval2_one
#print axioms IUT.zpEval2_pow
#print axioms IUT.eisRing
#print axioms IUT.eisOf
#print axioms IUT.eis_rpow_mk
#print axioms IUT.eis_lambda_pow
#print axioms IUT.eis_one_ne_zero
#print axioms IUT.eisOf_lambda_torsion_shape
#print axioms IUT.eisF_zero
#print axioms IUT.eisF_lambda
#print axioms IUT.lambda_all_torsion
#print axioms IUT.eis_lambda_ne_zero
#print axioms IUT.eisOf_compat_f
#print axioms IUT.eisIter_compat
#print axioms IUT.zpEval2Seg_rsum
#print axioms IUT.nilpotent_cauchy_mul
#print axioms IUT.zpEval3_mul
#print axioms IUT.zpEval3_one
#print axioms IUT.zpEval3_pow
#print axioms IUT.zpPow_eq_rpow
#print axioms IUT.eisF_semilinear
#print axioms IUT.conj_is_torsion
#print axioms IUT.conj_ne_zero
#print axioms IUT.conj_distinct
#print axioms IUT.teich_conj_torsion
#print axioms IUT.teich_conj_ne_zero
#print axioms IUT.teich_conj_distinct
#print axioms IUT.lambda_one_torsion_family
#print axioms IUT.lambda_one_family_distinct
#print axioms IUT.ramifiedEntrance
#print axioms IUT.ramified_entrance_exists
#print axioms IUT.zpEval3_liftYZ
#print axioms IUT.zpEval2_ps2X
#print axioms IUT.zpEval3_ps3X
#print axioms IUT.zpEval2_closed'
#print axioms IUT.proj_xyz_pow_low
#print axioms IUT.proj_Seg3_powpow_high
#print axioms IUT.zpEval3Seg_ps23Comp
#print axioms IUT.zpEval3_ps23Comp
#print axioms IUT.lt_point_assoc
#print axioms IUT.psScale_mul
#print axioms IUT.psScale_eisPoly
#print axioms IUT.eisAut
#print axioms IUT.eisAut_const
#print axioms IUT.eisAut_lambda
#print axioms IUT.eisAut_comp
#print axioms IUT.eisAut_one
#print axioms IUT.eisGal_mul
#print axioms IUT.eisGal_distinct
#print axioms IUT.eisAut_eisF
#print axioms IUT.wsum_supported
#print axioms IUT.lMul_coeff_window
#print axioms IUT.lAdd_coeff_assoc
#print axioms IUT.lAdd_coeff_neg
#print axioms IUT.lMul_coeff_distrib
#print axioms IUT.lMul_coeff_comm
#print axioms IUT.wsum_shift
#print axioms IUT.lMul_coeff_assoc
#print axioms IUT.lMul_coeff_one
#print axioms IUT.laurentRing
#print axioms IUT.laurentOf
#print axioms IUT.eisGal_residue
#print axioms IUT.recRam_mul
#print axioms IUT.eisGal_principal_trivial
#print axioms IUT.eisGal_faithful
#print axioms IUT.recRamLevelOne
#print axioms IUT.recRam_exists
#print axioms IUT.recRam_fixes_base
#print axioms IUT.isgn_succ
#print axioms IUT.tri_bound
#print axioms IUT.theta
#print axioms IUT.theta_zero_coeff
#print axioms IUT.uMon_mul_coeff
#print axioms IUT.uMon_mul_uMon
#print axioms IUT.laurent_uMon_mul
#print axioms IUT.uShift_add
#print axioms IUT.laurent_uMon_unit
#print axioms IUT.tri_step
#print axioms IUT.tri_le
#print axioms IUT.theta_funeq_coeff
#print axioms IUT.theta_funeq
#print axioms IUT.eisIter_succ_comm
#print axioms IUT.eisIter_add
#print axioms IUT.eisTorsion_zero
#print axioms IUT.eisTorsion_mono
#print axioms IUT.eisTorsion_lambda
#print axioms IUT.eisTorsion_step
#print axioms IUT.eisAut_eisIter
#print axioms IUT.eisAut_preserves_torsion
#print axioms IUT.eisIter_semilinear
#print axioms IUT.eisTorsion_conj_scale
#print axioms IUT.eisTorsionTower
#print axioms IUT.eisTorsionTower_exists
#print axioms IUT.eisTorsion_galois_orbit
#print axioms IUT.negPow_neg
#print axioms IUT.tCoeff_one
#print axioms IUT.tCoeff_eq
#print axioms IUT.gauss_bridge
#print axioms IUT.tCoeff_shift
#print axioms IUT.thetaIter_succ
#print axioms IUT.thetaIter_even
#print axioms IUT.thetaIter_odd
#print axioms IUT.negPow_isgn
#print axioms IUT.theta_gauss
#print axioms IUT.eisF_factor
#print axioms IUT.eisTorsion_one_classify
#print axioms IUT.lambda_eis_equation
#print axioms IUT.conj_eis_equation
#print axioms IUT.eisUpper
#print axioms IUT.eisUpper_exists
#print axioms IUT.Grp.pow_add
#print axioms IUT.Grp.mul_inv_rev
#print axioms IUT.Grp.central_pow
#print axioms IUT.tateRel_trans
#print axioms IUT.tateRel_mul
#print axioms IUT.tateRel_inv
#print axioms IUT.tateGrp
#print axioms IUT.tate_exact
#print axioms IUT.tate_q_one
#print axioms IUT.tate_ker
#print axioms IUT.tate_shift_trivial
#print axioms IUT.tate_deck_collapse
#print axioms IUT.tri_nat
#print axioms IUT.tri_int
#print axioms IUT.theta_gauss_tri
#print axioms IUT.theta_pow_one
#print axioms IUT.thetaSection_mul
#print axioms IUT.tri_cocycle
#print axioms IUT.theta_section_rigid
#print axioms IUT.monoThetaWitness
#print axioms IUT.mono_theta_exists
#print axioms IUT.neZeroAt_mono
#print axioms IUT.zpValDecompose
#print axioms IUT.neZeroAt_one_mul
#print axioms IUT.zp_mul_ne_zero
#print axioms IUT.zp_ne_zero_mul
#print axioms IUT.zpDomainData
#print axioms IUT.zpDomain_nonempty
#print axioms IUT.cube_expand
#print axioms IUT.ssq_closed
#print axioms IUT.stri_closed
#print axioms IUT.sq_exponent
#print axioms IUT.ssq_stri
#print axioms IUT.cube_le_ssq
#print axioms IUT.gaussianVolume
#print axioms IUT.gaussian_volume_exists
#print axioms IUT.zres
#print axioms IUT.res1_unit_not_dvd
#print axioms IUT.res1_mul_congr
#print axioms IUT.recInertia_mul
#print axioms IUT.recInertia_principal
#print axioms IUT.recInertia_lambda
#print axioms IUT.recLevelOne_mul_unram
#print axioms IUT.recLevelOne_mul_ram
#print axioms IUT.recLevelOne_ker
#print axioms IUT.recGluing
#print axioms IUT.recGluing_exists
#print axioms IUT.eisCoeff
#print axioms IUT.eisNeZeroAt_ne_zero
#print axioms IUT.eisOf_injective
#print axioms IUT.eisNeZeroAt_lambda_mul
#print axioms IUT.eis_lambda_mul_ne_zero
#print axioms IUT.eis_lambda_division
#print axioms IUT.eis_residue_mul
#print axioms IUT.eis_unit_mul_ne_zero
#print axioms IUT.eisDomainData
#print axioms IUT.eisDomain_nonempty
#print axioms IUT.endo_eisF_comm
#print axioms IUT.endo_eisIter_comm
#print axioms IUT.endo_preserves_torsion
#print axioms IUT.endo_lambda_torsion
#print axioms IUT.endo_lambda_classify
#print axioms IUT.endo_lambda_root
#print axioms IUT.eisEndoRigidity
#print axioms IUT.eisEndoRigidity_exists
#print axioms IUT.geom_factor
#print axioms IUT.qCoeff_peel
#print axioms IUT.lin_div
#print axioms IUT.pEval_div
#print axioms IUT.pEval_root_factor
#print axioms IUT.roots_bound
#print axioms IUT.pEval_bin
#print axioms IUT.bin_roots_bound
#print axioms IUT.eis_roots_bound
#print axioms IUT.eisNeZeroAt_lambda_wrap_rev
#print axioms IUT.eisDivLambda_spec
#print axioms IUT.eisValDecompose
#print axioms IUT.eis_valuation_exists
#print axioms IUT.eis_lambda_pow_mul_witness
#print axioms IUT.eis_lambda_pow_mul_ne_zero
#print axioms IUT.eis_mul_neZeroAt_exists
#print axioms IUT.eis_mul_ne_zero
#print axioms IUT.eis_ne_zero_mul
#print axioms IUT.eisDomain2Data
#print axioms IUT.eisDomain2_nonempty
#print axioms IUT.ssq_eq_sumSq
#print axioms IUT.sumSq_closed
#print axioms IUT.cube_le_sumSq
#print axioms IUT.sumSq_tri_stri
#print axioms IUT.theorem311Premises
#print axioms IUT.premises_exist
#print axioms IUT.premises_then_szpiro
#print axioms IUT.intVolumeTheory
#print axioms IUT.intVolumeTheory_consistent
#print axioms IUT.theta_volume_cube_bound
#print axioms IUT.sumSq_closed_int
#print axioms IUT.demoSkeleton_cor312
#print axioms IUT.volumeModelData
#print axioms IUT.volumeModelData_exists
#print axioms IUT.eis_root_meets_family
#print axioms IUT.eis_torsion_classify_full
#print axioms IUT.endo_lambda_meets_family
#print axioms IUT.eis_root_meets_family_dn
#print axioms IUT.lambdaClassify
#print axioms IUT.lambdaClassify_exists
#print axioms IUT.reflRep_involutive
#print axioms IUT.isgn_neg_succ
#print axioms IUT.theta_refl_coeff
#print axioms IUT.theta_refl
#print axioms IUT.theta_refl_eq_funeq
#print axioms IUT.thetaRelMod_mul
#print axioms IUT.thetaGrpMod
#print axioms IUT.theta_comm_mod
#print axioms IUT.mono_theta_cyclotomic_rigidity_mod
#print axioms IUT.thetaSectionMod_mul
#print axioms IUT.tri_period_dvd
#print axioms IUT.thetaSectionMod_period
#print axioms IUT.thetaGroupModData
#print axioms IUT.thetaGroupMod_exists
#print axioms IUT.nsum_congr
#print axioms IUT.nsum_mul_right
#print axioms IUT.efSum
#print axioms IUT.inertExt_sum
#print axioms IUT.splitExt_sum
#print axioms IUT.ramifiedExt_sum
#print axioms IUT.semiLocalFrobenioid
#print axioms IUT.decompPullback
#print axioms IUT.normDeg_add
#print axioms IUT.normDeg_frob
#print axioms IUT.normDeg_linear
#print axioms IUT.efg_identity
#print axioms IUT.efg_deg
#print axioms IUT.efg_pullback
#print axioms IUT.inert_efg
#print axioms IUT.split_efg
#print axioms IUT.ramified_efg
#print axioms IUT.normFunctor
#print axioms IUT.norm_pullback_obj
#print axioms IUT.norm_pullback_hom_d
#print axioms IUT.norm_pullback_hom_c
#print axioms IUT.semiLocal_iso_objects_eq
#print axioms IUT.semiLocalFrobenioid_gaunt
#print axioms IUT.semiLocal_iso_unique
#print axioms IUT.semiLocal_rigid
#print axioms IUT.nnqAdd_assoc
#print axioms IUT.nnqAdd_comm
#print axioms IUT.nnqOfNat_add
#print axioms IUT.nnq_div_cancel
#print axioms IUT.radd_assoc
#print axioms IUT.realify_add
#print axioms IUT.realify_frob
#print axioms IUT.degR_add
#print axioms IUT.degR_frob
#print axioms IUT.degR_realify
#print axioms IUT.rdiv_divisible
#print axioms IUT.qdiv_not_divisible
#print axioms IUT.realification_gains_divisibility
#print axioms IUT.realFrobenioid
#print axioms IUT.real_pilot_division
#print axioms IUT.realifyFunctor
#print axioms IUT.real_iso_objects_eq
#print axioms IUT.real_gaunt_isoUnique
#print axioms IUT.archFrobenioid
#print axioms IUT.arch_divisible
#print axioms IUT.arch_pilot_division
#print axioms IUT.nonarch_pilot_obstruction
#print axioms IUT.arch_vs_nonarch
#print axioms IUT.localArchFunctor
#print axioms IUT.local_realification_gains_divisibility
#print axioms IUT.mixedAdd_assoc
#print axioms IUT.mixedFrob_add
#print axioms IUT.mixedFrob_frob
#print axioms IUT.degMixed_add
#print axioms IUT.degMixed_frob
#print axioms IUT.mixedFrobenioid
#print axioms IUT.mixed_iso_objects_eq
#print axioms IUT.mixed_gaunt_isoUnique
#print axioms IUT.mixed_divisibility_dichotomy
#print axioms IUT.mixed_pilot_division
#print axioms IUT.mixed_fin_zero_divisible
#print axioms IUT.mixed_single_not_divisible
#print axioms IUT.ltEnd_gAdd_comm
#print axioms IUT.ltEnd_gAdd_assoc
#print axioms IUT.ltEnd_gMul_comm
#print axioms IUT.ltEnd_gMul_assoc
#print axioms IUT.ltEnd_left_distrib
#print axioms IUT.ltEnd_right_distrib
#print axioms IUT.ltEnd_gAdd_zero
#print axioms IUT.ltEnd_gAdd_neg
#print axioms IUT.ltEnd_gMul_one
#print axioms IUT.ltEndRingData
#print axioms IUT.ltEndRing_exists
#print axioms IUT.zpPow_zpPow
#print axioms IUT.zpPow_mul_dist
#print axioms IUT.zpPow_zpOne
#print axioms IUT.zpPow_one_exp
#print axioms IUT.isMuRoot_mul
#print axioms IUT.isMuRoot_pow
#print axioms IUT.muGrp
#print axioms IUT.muGrp_comm
#print axioms IUT.muRoot_pow_p
#print axioms IUT.muRoot_pow_p_pow
#print axioms IUT.muRoot_level_one_unit
#print axioms IUT.teichBar
#print axioms IUT.teichBar_mul
#print axioms IUT.teichBar_level_one
#print axioms IUT.teichBar_of_muRoot
#print axioms IUT.muRoot_iff_teich
#print axioms IUT.isZpUnit_of_muRoot
#print axioms IUT.teich_inj
#print axioms IUT.teichBar_inj
#print axioms IUT.isZmodUnit_mul
#print axioms IUT.isZmodUnit_pow
#print axioms IUT.zmodUnit_inv_mul
#print axioms IUT.zmodUnits
#print axioms IUT.zmodUnits_comm
#print axioms IUT.isZmodUnit_of_muRoot
#print axioms IUT.isMuRoot_teichBar
#print axioms IUT.muToUnits
#print axioms IUT.unitsToMu
#print axioms IUT.muUnitsIsoData
#print axioms IUT.muUnitsIso_exists
#print axioms IUT.sub_one_emod_congr
#print axioms IUT.zmodIsOne_true
#print axioms IUT.zmodIsOne_one
#print axioms IUT.zmodIsOne_false
#print axioms IUT.zmodMul_assoc
#print axioms IUT.zmodOne_mul
#print axioms IUT.zmodPow_add
#print axioms IUT.zmodPow_mul
#print axioms IUT.zmodPow_one_base
#print axioms IUT.zmodUnit_pow_card
#print axioms IUT.ordSearch_spec
#print axioms IUT.zmodOrd_spec
#print axioms IUT.zmodOrd_pow_eq_one
#print axioms IUT.zmodOrd_pos
#print axioms IUT.zmodOrd_le
#print axioms IUT.zmodOrd_dvd
#print axioms IUT.zmodOrd_dvd_card
#print axioms IUT.zmod_unit_cancel
#print axioms IUT.zmodOrd_powers_distinct
#print axioms IUT.zmodOrd_pow_div
#print axioms IUT.prime_factor_exists
#print axioms IUT.prime_pow_extract
#print axioms IUT.prime_dvd_prime_pow
#print axioms IUT.coprime_dvd_cancel
#print axioms IUT.coprime_mul_dvd
#print axioms IUT.coprime_of_not_dvd_prime_pow
#print axioms IUT.dvd_or_valuation_gap
#print axioms IUT.zmodPow_mul_dist
#print axioms IUT.zmodPow_succ
#print axioms IUT.zmodMul_one
#print axioms IUT.zmod_no_zero_div
#print axioms IUT.zmodRing_one_ne_zero
#print axioms IUT.zmodPow_eq_rpow
#print axioms IUT.zmodOrd_mul_coprime
#print axioms IUT.zmodOrd_combine
#print axioms IUT.exponent_fold
#print axioms IUT.exponent_element
#print axioms IUT.primitive_root_exists
#print axioms IUT.zmodEqb_true
#print axioms IUT.zmodEqb_false
#print axioms IUT.zpPow_zero
#print axioms IUT.teichBar_pow
#print axioms IUT.generator_covers
#print axioms IUT.zmodUnits_cyclic
#print axioms IUT.mu_powers_distinct
#print axioms IUT.mu_cyclic
#print axioms IUT.ltPoly_factor
#print axioms IUT.psX_factor
#print axioms IUT.eisRel_comp_ideal
#print axioms IUT.eisBr_zero
#print axioms IUT.eisBr_one
#print axioms IUT.eisBr_add_series
#print axioms IUT.eisBr_mul_series
#print axioms IUT.ltSol_pi
#print axioms IUT.eisBr_pi_mul
#print axioms IUT.eisBr_pi_pow
#print axioms IUT.eisBr_unit_ne_zero
#print axioms IUT.eisBr_eq_zero_iff
#print axioms IUT.lambdaModuleData
#print axioms IUT.lambdaModule_exists
#print axioms IUT.psSingle_mul_single
#print axioms IUT.psSingleOne_pow
#print axioms IUT.psScale_eq_comp
#print axioms IUT.psComp_smul_left
#print axioms IUT.psSmul_add
#print axioms IUT.psSmul_swap
#print axioms IUT.psPow_smul
#print axioms IUT.rpow_fixed_of_root
#print axioms IUT.ltPoly_dilate
#print axioms IUT.ltSol_dilate
#print axioms IUT.psScale_ltSol
#print axioms IUT.psSmul_eq_psC_mul
#print axioms IUT.eisAut_eisBr
#print axioms IUT.eisBr_conj_scale
#print axioms IUT.zpPow_eq_rpow_zp
#print axioms IUT.eisAut_teich_eisBr
#print axioms IUT.psMul_psX_coeff
#print axioms IUT.psX_shift_split
#print axioms IUT.psZero_mul
#print axioms IUT.psComp_psZero_right
#print axioms IUT.ps21Comp_add
#print axioms IUT.ps21Comp_Y
#print axioms IUT.ps21Comp_split
#print axioms IUT.lt2Sol_row_zero
#print axioms IUT.eisRel_FG_absorb
#print axioms IUT.ltSol_teich
#print axioms IUT.eisBr_principal
#print axioms IUT.eisBr_reciprocity
#print axioms IUT.ramifiedReciprocityData
#print axioms IUT.ramifiedReciprocity_exists
#print axioms IUT.mulMod_assoc
#print axioms IUT.mulMod_ne_zero
#print axioms IUT.flInv_exists
#print axioms IUT.flInv_spec
#print axioms IUT.flUnits
#print axioms IUT.flUnits_comm
#print axioms IUT.rpow_pi_val_zero
#print axioms IUT.zpTerm_val_zero
#print axioms IUT.zpSum_val_stable
#print axioms IUT.zpSeriesSum_partial
#print axioms IUT.zpSeriesSum_add
#print axioms IUT.zpSeriesSum_head
#print axioms IUT.padicSeriesData
#print axioms IUT.padicSeries_exists
#print axioms IUT.quotCRing
#print axioms IUT.quotOf
#print axioms IUT.quot_exact_ideal
#print axioms IUT.quot_rpow_mk
#print axioms IUT.psSmul_psX
#print axioms IUT.rpow_psX
#print axioms IUT.towerStep_shape
#print axioms IUT.towerLevel
#print axioms IUT.tower_shape
#print axioms IUT.ringFIter_hom
#print axioms IUT.tower_base_torsion
#print axioms IUT.tower_torsion
#print axioms IUT.eisTowerData
#print axioms IUT.eisTower_exists
#print axioms IUT.negMod_mulMod_left
#print axioms IUT.pmCong
#print axioms IUT.flStar
#print axioms IUT.flStar_comm
#print axioms IUT.flStar_rep
#print axioms IUT.flStarData
#print axioms IUT.zpSeriesSum_zero_fun
#print axioms IUT.zpSeriesSum_smul
#print axioms IUT.zpSeriesSum_split
#print axioms IUT.zpSeriesSum_tail_dvd
#print axioms IUT.padicSeriesSplitData
#print axioms IUT.towerStepPoly_coeff_zero
#print axioms IUT.eisResFun_congr
#print axioms IUT.eisRes
#print axioms IUT.eisRes_pi
#print axioms IUT.eisRes_lambda
#print axioms IUT.towerResFun_congr
#print axioms IUT.towerResStep
#print axioms IUT.towerResStep_pi
#print axioms IUT.towerResStep_lam
#print axioms IUT.towerRes
#print axioms IUT.towerRes_compat
#print axioms IUT.tower_one_ne_zero
#print axioms IUT.tower_lam_not_unit
#print axioms IUT.tower_pi_not_unit
#print axioms IUT.residueTowerData
#print axioms IUT.residueTower_exists
#print axioms IUT.ringF_zero
#print axioms IUT.ringFIter_succ_comm
#print axioms IUT.towerTorsion_zero
#print axioms IUT.towerTorsion_mono
#print axioms IUT.towerTorsion_step
#print axioms IUT.towerTorsion_hom
#print axioms IUT.ringF_eisF
#print axioms IUT.ringFIter_eisIter
#print axioms IUT.towerTorsion_base_iff
#print axioms IUT.tower_lam_torsion
#print axioms IUT.tower_lam_torsion_ge
#print axioms IUT.tower_iota_lam_torsion
#print axioms IUT.towerTorsionData
#print axioms IUT.towerTorsionData_exists
#print axioms IUT.rpow_rpow
#print axioms IUT.ringF_pi_zero
#print axioms IUT.ringFIter_pi_zero
#print axioms IUT.one_le_pow
#print axioms IUT.zmod_rpow_eq_zero
#print axioms IUT.towerTorsion_res_zero
#print axioms IUT.towerTorsion_not_unit
#print axioms IUT.torsionResidueData
#print axioms IUT.torsionResidue_exists
#print axioms IUT.geomSeq_zero
#print axioms IUT.geomSeq_succ
#print axioms IUT.geomSeq_shift
#print axioms IUT.principalUnitInv_shift
#print axioms IUT.principalUnitInv_eq
#print axioms IUT.principal_unit_mul_inv
#print axioms IUT.principal_unit_is_unit
#print axioms IUT.padicGeometricData
#print axioms IUT.padicGeometric_exists
#print axioms IUT.thetaNeg
#print axioms IUT.thetaNeg_involutive
#print axioms IUT.thetaNeg_center
#print axioms IUT.thetaNeg_section_mul
#print axioms IUT.thetaNeg_section_inv
#print axioms IUT.thetaRelMod_neg
#print axioms IUT.thetaNegMod
#print axioms IUT.thetaNegMod_involutive
#print axioms IUT.thetaNegMod_red
#print axioms IUT.thetaNegMod_section
#print axioms IUT.thetaNeg_label_center
#print axioms IUT.thetaPMData
#print axioms IUT.thetaPM_exists
#print axioms IUT.ratRing
#print axioms IUT.ratOfInt
#print axioms IUT.quot_exact_rat
#print axioms IUT.ratOfInt_inj
#print axioms IUT.qLe_refl
#print axioms IUT.qLe_trans
#print axioms IUT.qLe_antisym
#print axioms IUT.qLe_total
#print axioms IUT.qLe_add
#print axioms IUT.qLe_mul_nonneg
#print axioms IUT.qMul_inv
#print axioms IUT.qAbs_add_le
#print axioms IUT.qAbs_mul
#print axioms IUT.rat_archimedean
#print axioms IUT.ratFieldData
#print axioms IUT.ratField_exists
#print axioms IUT.prime_odd
#print axioms IUT.flStar_rep_unique
#print axioms IUT.flStarRep
#print axioms IUT.flStarRep_range
#print axioms IUT.flStarRep_lt
#print axioms IUT.flStarRep_section
#print axioms IUT.flStarRep_complete
#print axioms IUT.flStarRep_inj
#print axioms IUT.flStarCountData
#print axioms IUT.flStarCountData_nonempty
#print axioms IUT.teich_val_one
#print axioms IUT.teich_inv_exists
#print axioms IUT.unit_decomposition_unique
#print axioms IUT.zp_unit_inv_exists
#print axioms IUT.zp_unit_mul
#print axioms IUT.zp_unit_one
#print axioms IUT.zpUnitGroupData
#print axioms IUT.zpUnitGroup_exists
#print axioms IUT.qFrac_le
#print axioms IUT.qFrac_add
#print axioms IUT.qLe_add_two
#print axioms IUT.qAbs_neg
#print axioms IUT.qAbs_sub_split
#print axioms IUT.int_eps_cancel
#print axioms IUT.qLe_of_forall_add_frac
#print axioms IUT.qToReal
#print axioms IUT.realEq_refl
#print axioms IUT.realEq_symm
#print axioms IUT.realEq_trans
#print axioms IUT.realAdd
#print axioms IUT.realNeg
#print axioms IUT.realAdd_congr_left
#print axioms IUT.realAdd_congr_right
#print axioms IUT.realAdd_comm
#print axioms IUT.realAdd_assoc
#print axioms IUT.realAdd_zero
#print axioms IUT.realAdd_neg
#print axioms IUT.qToReal_add
#print axioms IUT.regularRealData
#print axioms IUT.regularReal_exists
#print axioms IUT.psMul_coeff_one
#print axioms IUT.towerStepPoly_coeff_one
#print axioms IUT.neg_eq_zero_iff
#print axioms IUT.towerLam_ne_zero
#print axioms IUT.tower_lam_step_ne_zero
#print axioms IUT.tower_lam_one_ne_zero_of_base
#print axioms IUT.towerNonzeroData
#print axioms IUT.towerNonzero_exists
#print axioms IUT.int_ediv_unique
#print axioms IUT.prFloor_spec
#print axioms IUT.ratRel_floor
#print axioms IUT.qFloor
#print axioms IUT.qFloor_le
#print axioms IUT.qFloor_lt
#print axioms IUT.qFloorNat_upper
#print axioms IUT.qAbs_nonneg
#print axioms IUT.qAbs_le_add_sub
#print axioms IUT.rBound_spec
#print axioms IUT.ratFloorData
#print axioms IUT.ratFloor_exists
#print axioms IUT.order_l_exists
#print axioms IUT.mu_l_root
#print axioms IUT.mu_l_powers_distinct
#print axioms IUT.mu_l_pow_root
#print axioms IUT.mu_l_complete
#print axioms IUT.mu_l_zp_exists
#print axioms IUT.muLSubgroupData
#print axioms IUT.muLSubgroup_exists
#print axioms IUT.eisCoeffZp_val_stable
#print axioms IUT.eisCoeffStab
#print axioms IUT.eisCoeffZp_head
#print axioms IUT.eisCoeffStab_rec
#print axioms IUT.eisCoeffStab_solve
#print axioms IUT.weierstrass_division
#print axioms IUT.eisCoeffZp_zero_series
#print axioms IUT.eisCoeff_faithful
#print axioms IUT.zp_pi_regular
#print axioms IUT.eisLambda_regular
#print axioms IUT.tower_lam_two_ne_zero
#print axioms IUT.eisFaithfulData
#print axioms IUT.eisFaithful_exists
#print axioms IUT.zpPow_add
#print axioms IUT.zpPow_mul_period
#print axioms IUT.int_emod_unique
#print axioms IUT.int_emod_congr
#print axioms IUT.centerToMu
#print axioms IUT.centerToMu_congr
#print axioms IUT.centerToMu_add
#print axioms IUT.centerToMu_zero
#print axioms IUT.centerToMu_one_gen
#print axioms IUT.centerToMu_faithful
#print axioms IUT.centerToMu_period
#print axioms IUT.theta_center_mul
#print axioms IUT.theta_center_descend
#print axioms IUT.theta_center_to_mu_hom
#print axioms IUT.theta_center_neg_invariant
#print axioms IUT.cyclotomicSyncData
#print axioms IUT.cyclotomicSync_exists
#print axioms IUT.qMul_comm
#print axioms IUT.qLe_mul_right
#print axioms IUT.qAbs_mul_sub
#print axioms IUT.mulIdx_cast
#print axioms IUT.ratOfInt_mul_qFrac
#print axioms IUT.qFrac_two_bound
#print axioms IUT.mul_seq_reg
#print axioms IUT.rmul
#print axioms IUT.rmul_comm
#print axioms IUT.rmul_one
#print axioms IUT.rmul_zero
#print axioms IUT.qToReal_mul
#print axioms IUT.mul_seq_congr
#print axioms IUT.rmul_congr_left
#print axioms IUT.rmul_congr_right
#print axioms IUT.realMulData
#print axioms IUT.realMul_exists
#print axioms IUT.qLe_abs_move
#print axioms IUT.isPos_spread
#print axioms IUT.isPos_congr
#print axioms IUT.isPos_zero_false
#print axioms IUT.isPos_add
#print axioms IUT.rLt_congr
#print axioms IUT.rLt_irrefl
#print axioms IUT.rLt_trans
#print axioms IUT.rLt_cotrans
#print axioms IUT.realOrderData
#print axioms IUT.realOrder_exists
#print axioms IUT.centerFun_congr
#print axioms IUT.centerToMuMod
#print axioms IUT.centerToMuMod_red_center
#print axioms IUT.centerToMuMod_mul_center
#print axioms IUT.centerToMuMod_faithful_center
#print axioms IUT.centerToMuMod_period_center
#print axioms IUT.centerToMuMod_neg
#print axioms IUT.thetaCenterModData
#print axioms IUT.thetaCenterMod_exists
#print axioms IUT.intAbs_sub_intAbs
#print axioms IUT.qAbs_abs_sub_abs
#print axioms IUT.rabs
#print axioms IUT.rabs_congr
#print axioms IUT.rabs_neg
#print axioms IUT.rabs_add_le
#print axioms IUT.rabs_mul
#print axioms IUT.realAbsData
#print axioms IUT.realAbs_exists
#print axioms IUT.qAbs_sub_comm
#print axioms IUT.rlim
#print axioms IUT.rlim_close
#print axioms IUT.rlim_unique
#print axioms IUT.realCompleteData
#print axioms IUT.realComplete_exists
#print axioms IUT.qFrac_mul
#print axioms IUT.isPos_lower
#print axioms IUT.isPos_mul
#print axioms IUT.rLt_mul_pos
#print axioms IUT.realPosMulData
#print axioms IUT.realPosMul_exists
#print axioms IUT.qLe_sub_move
#print axioms IUT.qSub_le_of_le
#print axioms IUT.rLe_of_realEq
#print axioms IUT.rLe_trans
#print axioms IUT.rLe_antisym
#print axioms IUT.rLe_congr
#print axioms IUT.rLe_add
#print axioms IUT.rLt_le
#print axioms IUT.rLt_not_le
#print axioms IUT.realLeData
#print axioms IUT.realLe_exists
#print axioms IUT.qdegQ_add
#print axioms IUT.qdegQ_frob
#print axioms IUT.qToReal_mono
#print axioms IUT.rlogVol_add
#print axioms IUT.rlogVol_frob
#print axioms IUT.rlogVol_zero
#print axioms IUT.rlogVol_nonneg
#print axioms IUT.rlogVol_mono
#print axioms IUT.qdegQ_compat_realify
#print axioms IUT.rlogVol_compat
#print axioms IUT.logVolBridgeData
#print axioms IUT.logVolBridge_exists
#print axioms IUT.natToReal_mono
#print axioms IUT.natToReal_add
#print axioms IUT.natToReal_mul
#print axioms IUT.ssq_closed_real
#print axioms IUT.stri_closed_real
#print axioms IUT.ssq_stri_real
#print axioms IUT.cube_le_ssq_real
#print axioms IUT.volumeRealData
#print axioms IUT.volumeReal_exists
#print axioms IUT.gaussDiv_deg
#print axioms IUT.rlogVol_gauss_eq
#print axioms IUT.rlogVol_gauss_closed
#print axioms IUT.rlogVol_gauss_bound
#print axioms IUT.rlogVol_gauss_frob
#print axioms IUT.gaussianDivisorData
#print axioms IUT.gaussianDivisor_exists
#print axioms IUT.theorem311RealPremises
#print axioms IUT.premises311Real_exist
#print axioms IUT.real_theta_bookkeeping_holds
#print axioms IUT.real_volume_lower_holds
#print axioms IUT.gaussDiv_deg_w
#print axioms IUT.rlogVol_gauss_w
#print axioms IUT.wssq_mono
#print axioms IUT.rlogVol_gauss_w_mono
#print axioms IUT.wssq_one
#print axioms IUT.rlogVol_gauss_w_one
#print axioms IUT.wssq_lower
#print axioms IUT.rlogVol_gauss_w_bound
#print axioms IUT.weightedGaussData
#print axioms IUT.weightedGauss_exists
#print axioms IUT.not_lt_le
#print axioms IUT.le_iff_not_lt
#print axioms IUT.lt_iff_not_le
#print axioms IUT.realOrderCompleteData
#print axioms IUT.realOrderComplete_exists
#print axioms IUT.section_gauss_component
#print axioms IUT.funeq_gauss_descent
#print axioms IUT.funeqDict
#print axioms IUT.dict_multiplicative
#print axioms IUT.gauss_additive_with_cocycle
#print axioms IUT.dict_pm
#print axioms IUT.funeqLiftData
#print axioms IUT.funeqLift_exists
#print axioms IUT.qAdd_mul
#print axioms IUT.qSub_mul
#print axioms IUT.scalar_distrib_core
#print axioms IUT.rmul_scalar_distrib
#print axioms IUT.rmul_scalar_distrib_nat
#print axioms IUT.scalarDistribData
#print axioms IUT.scalarDistrib_exists
#print axioms IUT.qMax_cases
#print axioms IUT.qLe_max_left
#print axioms IUT.qLe_max_right
#print axioms IUT.qMax_le
#print axioms IUT.rmax
#print axioms IUT.rLe_max_left
#print axioms IUT.rLe_max_right
#print axioms IUT.rmax_least
#print axioms IUT.realVolumeTheory
#print axioms IUT.realVolumeTheory_consistent
#print axioms IUT.intToReal_mono
#print axioms IUT.intToReal_reflect
#print axioms IUT.real_cor312_vol
#print axioms IUT.cor312_of_realMultiradial
#print axioms IUT.szpiro_of_realMultiradial
#print axioms IUT.realMultiradial_consistent
#print axioms IUT.realVolumeTheoryData
#print axioms IUT.realVolumeTheoryData_exists
#print axioms IUT.qMax_comm
#print axioms IUT.qMax_idem
#print axioms IUT.qMax_assoc
#print axioms IUT.rmax_comm
#print axioms IUT.rmax_idem
#print axioms IUT.rmax_assoc
#print axioms IUT.rmax_congr
#print axioms IUT.realMaxLawsData
#print axioms IUT.realMaxLaws_exists
#print axioms IUT.gaussSkeleton
#print axioms IUT.gaussPilotRep
#print axioms IUT.gaussPilot_cor312
#print axioms IUT.gaussPilot_vol_theta
#print axioms IUT.gaussPilotData
#print axioms IUT.gaussPilot_exists
#print axioms IUT.intToReal_natCast
#print axioms IUT.intToReal_add
#print axioms IUT.intToReal_mul
#print axioms IUT.intToReal_neg
#print axioms IUT.intToReal_sub
#print axioms IUT.rlogVol_eq_intToReal
#print axioms IUT.natToReal_reflect
#print axioms IUT.intRealBridgeData
#print axioms IUT.intRealBridge_exists
#print axioms IUT.tri_adjacent_sq
#print axioms IUT.tri_adjacent_sq_real
#print axioms IUT.ssq_stri_split
#print axioms IUT.ssq_stri_split_real
#print axioms IUT.dict_adjacent_centers
#print axioms IUT.triSquareData
#print axioms IUT.triSquare_exists
#print axioms IUT.rsum_tail_single
#print axioms IUT.psMul_X_coeff_succ
#print axioms IUT.psMul_shift_zero
#print axioms IUT.towerLam_regular_step
#print axioms IUT.tower_lam_regular
#print axioms IUT.regular_ne_zero
#print axioms IUT.tower_lam_ne_zero_all
#print axioms IUT.lambdaPropagationData
#print axioms IUT.lambdaPropagation_exists
#print axioms IUT.regular_one
#print axioms IUT.regular_mul
#print axioms IUT.regular_rpow
#print axioms IUT.regular_pow_ne_zero
#print axioms IUT.tower_lam_pow_ne_zero_all
#print axioms IUT.zp_pi_regular_elem
#print axioms IUT.zp_one_ne_zero
#print axioms IUT.zp_pi_pow_ne_zero
#print axioms IUT.regularPowersData
#print axioms IUT.regularPowers_exists
#print axioms IUT.towerStepPoly_coeff_top
#print axioms IUT.towerStepPoly_coeff_other
#print axioms IUT.rsum_single_middle
#print axioms IUT.psMul_g_top_coeff
#print axioms IUT.poly_mul_g_bounded_zero
#print axioms IUT.poly_division_unique
#print axioms IUT.polyWeierstrassWitness
#print axioms IUT.polyWeierstrass_exists
#print axioms IUT.coreSubgroup
#print axioms IUT.core_le
#print axioms IUT.core_normal
#print axioms IUT.coreToCoset_equivariant
#print axioms IUT.coreToCoset_surjective
#print axioms IUT.core_hom_pointed
#print axioms IUT.coset_stabilizer_mem
#print axioms IUT.core_stabilizer_all
#print axioms IUT.core_aut_transitive
#print axioms IUT.galois_closure_model
#print axioms IUT.galoisClosureModelWitness
#print axioms IUT.galoisClosureModel_exists
#print axioms IUT.autOrbitRel_act
#print axioms IUT.gsetQuot
#print axioms IUT.gsetQuot_coeq
#print axioms IUT.gsetQuotLift_comp
#print axioms IUT.gsetQuot_univ
#print axioms IUT.gsetQuotientAxiom
#print axioms IUT.gset_satisfies_quotient
#print axioms IUT.gsetQuotientWitness
#print axioms IUT.gsetQuotient_exists
#print axioms IUT.rshift_eq
#print axioms IUT.qInv_mul_self
#print axioms IUT.qAbs_qInv_le
#print axioms IUT.qInv_sub_expand
#print axioms IUT.qInv_diff_le
#print axioms IUT.realEq_qconst_of_bound
#print axioms IUT.qFrac_sq_bound
#print axioms IUT.rinvPos
#print axioms IUT.rinvPos_mul_self
#print axioms IUT.pos_inv_exists
#print axioms IUT.realInvData
#print axioms IUT.realInv_exists
#print axioms IUT.isValAtLeast_zero
#print axioms IUT.isValAtLeast_step
#print axioms IUT.isValAtLeast_mono
#print axioms IUT.lam_pow_self_val
#print axioms IUT.lam_pow_val_le
#print axioms IUT.lam_pow_strict
#print axioms IUT.lam_pow_val_exact
#print axioms IUT.tower_lam_staircase
#print axioms IUT.tower_lam_val_exact
#print axioms IUT.lambdaValuationData
#print axioms IUT.lambdaValuation_exists
#print axioms IUT.psMul_single_g_coeff
#print axioms IUT.sub_top_bounded
#print axioms IUT.poly_division_exists
#print axioms IUT.poly_weierstrass_complete
#print axioms IUT.polyDivisionWitness
#print axioms IUT.polyDivision_exists_thm
#print axioms IUT.qAbs_of_nonneg
#print axioms IUT.qAbs_of_nonpos
#print axioms IUT.isPos_abs_cases
#print axioms IUT.rBound_neg
#print axioms IUT.rmul_neg_right
#print axioms IUT.rmul_neg_left
#print axioms IUT.realNeg_neg
#print axioms IUT.apart_inv_exists
#print axioms IUT.apartInvData
#print axioms IUT.apartInv_exists
#print axioms IUT.rLe_of_rate_bound
#print axioms IUT.realEq_of_rate_bound
#print axioms IUT.rmul_add_right
#print axioms IUT.rmul_add_left
#print axioms IUT.rmul_assoc_real
#print axioms IUT.realRingLawsData
#print axioms IUT.realRingLaws_exists
#print axioms IUT.cosetGSet
#print axioms IUT.cosetGSet_transitive
#print axioms IUT.gset_mono_injective
#print axioms IUT.cosetSection_section
#print axioms IUT.cosetGSet_connected
#print axioms IUT.coreRightMul_isIso
#print axioms IUT.cosetGSet_core_galois
#print axioms IUT.galois_closure_abstract
#print axioms IUT.cosetGaloisWitness
#print axioms IUT.cosetGalois_exists
#print axioms IUT.isIn2Pow_neg
#print axioms IUT.isIn2Pow_collapse
#print axioms IUT.psMul_g_coeff_three
#print axioms IUT.depth_of_bounded_image
#print axioms IUT.sep_poly_faithful
#print axioms IUT.zp_pow_mul_val_rep
#print axioms IUT.zp_separated
#print axioms IUT.zp_step_faithful
#print axioms IUT.towerSeparationData
#print axioms IUT.towerSeparation_exists
#print axioms IUT.constructiveOrderedFieldData
#print axioms IUT.constructiveOrderedField_exists
#print axioms IUT.real_field_complete_profile
#print axioms IUT.real_field_distrib
#print axioms IUT.natFact_le_divides
#print axioms IUT.intMulSubgroup
#print axioms IUT.intSub_le
#print axioms IUT.subgroup_ext
#print axioms IUT.abelian_core_eq
#print axioms IUT.intCoset_galois
#print axioms IUT.factorialTower
#print axioms IUT.galoisTower_inhabited_nontrivial
#print axioms IUT.factTower_fiber_nontrivial
#print axioms IUT.factorialTowerWitness
#print axioms IUT.factorialTower_exists
#print axioms IUT.gaussSkeletonW
#print axioms IUT.gaussPilotRepW
#print axioms IUT.gaussPilotW_cor312
#print axioms IUT.gaussPilotW_vol_theta
#print axioms IUT.gaussPilotW_volume_lower
#print axioms IUT.gaussPilotWeightedData
#print axioms IUT.gaussPilotWeighted_exists
#print axioms IUT.natConst_le_rBound
#print axioms IUT.rLe_mul_const_seq
#print axioms IUT.rLe_mul_natConst_left
#print axioms IUT.strict_evaluation_obstruction_real
#print axioms IUT.padding_necessary_real
#print axioms IUT.realObstructionData
#print axioms IUT.realObstruction_exists
#print axioms IUT.mul_middle4
#print axioms IUT.isValAtLeast_mul
#print axioms IUT.tower_isValAtLeast_mul
#print axioms IUT.lam_pow_mul_unit_strict
#print axioms IUT.tower_lam_pow_mul_unit_strict
#print axioms IUT.lambdaValMulData
#print axioms IUT.lambdaValMul_exists
#print axioms IUT.rinv_unique
#print axioms IUT.rinv_congr
#print axioms IUT.rmul_mul_mul_comm
#print axioms IUT.rmul_inv_mul
#print axioms IUT.apart_inv_unique
#print axioms IUT.realDivisionData
#print axioms IUT.realDivision_exists
#print axioms IUT.crGeomSum_succ
#print axioms IUT.geom_closed
#print axioms IUT.geom_closed_right
#print axioms IUT.geomSeriesData
#print axioms IUT.geomSeries_exists
#print axioms IUT.isValAtLeast_add
#print axioms IUT.isValAtLeast_neg
#print axioms IUT.isValAtLeast_smul
#print axioms IUT.isValAtLeast_pow
#print axioms IUT.lambdaIdealData
#print axioms IUT.lambdaIdeal_exists
#print axioms IUT.real_add_cancel_middle
#print axioms IUT.real_geom_closed
#print axioms IUT.realGeomData
#print axioms IUT.realGeom_exists
#print axioms IUT.realPow_add
#print axioms IUT.realPow_congr
#print axioms IUT.realPowData
#print axioms IUT.realPow_exists
#print axioms IUT.realPow_one
#print axioms IUT.realPow_mul_base
#print axioms IUT.realPow_mul_exp
#print axioms IUT.realPowMulData
#print axioms IUT.realPowMul_exists
#print axioms IUT.real_geom_rec_left
#print axioms IUT.real_geom_residual
#print axioms IUT.realGeomRecData
#print axioms IUT.realGeomRec_exists
#print axioms IUT.rabs_one
#print axioms IUT.rabs_idem
#print axioms IUT.rabs_pow
#print axioms IUT.realAbsPowData
#print axioms IUT.realAbsPow_exists
#print axioms IUT.geom_rec_left
#print axioms IUT.geom_residual
#print axioms IUT.geomSeriesRecData
#print axioms IUT.geomSeriesRec_exists
#print axioms IUT.realGeomSum_congr
#print axioms IUT.realGeomSum_incr
#print axioms IUT.realGeomCongrData
#print axioms IUT.realGeomCongr_exists
#print axioms IUT.isValAtLeast_ratio_mul
#print axioms IUT.isValAtLeast_geomSum_sub_one
#print axioms IUT.lambdaGeomData
#print axioms IUT.lambdaGeom_exists
#print axioms IUT.rLe_of_seq_le
#print axioms IUT.rabs_nonneg
#print axioms IUT.rLe_self_rabs
#print axioms IUT.rLe_neg_rabs
#print axioms IUT.realAbsLeData
#print axioms IUT.realAbsLe_exists
#print axioms IUT.rabs_triangle
#print axioms IUT.rLe_qToReal
#print axioms IUT.realAbsTriangleData
#print axioms IUT.realAbsTriangle_exists
#print axioms IUT.rabs_geomSum_le
#print axioms IUT.realGeomAbsData
#print axioms IUT.realGeomAbs_exists
#print axioms IUT.sub_one_eq_neg_of_add_eq_one
#print axioms IUT.isValAtLeast_inv_approx
#print axioms IUT.lambdaInvApproxData
#print axioms IUT.lambdaInvApprox_exists
#print axioms IUT.real_neg_of_add_eq_zero
#print axioms IUT.real_geom_inv_error
#print axioms IUT.rabs_geom_inv_error
#print axioms IUT.realGeomInvData
#print axioms IUT.realGeomInv_exists
#print axioms IUT.geometricSeriesProgramData
#print axioms IUT.geometricSeriesProgram_exists
#print axioms IUT.nat_geom_decay
#print axioms IUT.nat_geom_decay_modulus
#print axioms IUT.geomDecayNatData
#print axioms IUT.geomDecayNat_exists
#print axioms IUT.mul_idx_gap
#print axioms IUT.rmul_mid_gap
#print axioms IUT.rmul_le_seq
#print axioms IUT.rmul_le_mul_right
#print axioms IUT.rmul_le_mul_left
#print axioms IUT.realPow_nonneg
#print axioms IUT.realPow_le
#print axioms IUT.realMulOrderData
#print axioms IUT.realMulOrder_exists
#print axioms IUT.int_add_one_pow_pos
#print axioms IUT.qpow_frac_repr
#print axioms IUT.qpow_frac_le
#print axioms IUT.realPow_qToReal
#print axioms IUT.realPow_rabs_decay
#print axioms IUT.realGeomDecayData
#print axioms IUT.realGeomDecay_exists
#print axioms IUT.geom_inverse_converges
#print axioms IUT.geomConvergeData
#print axioms IUT.geomConverge_exists
#print axioms IUT.geom_sub_limit
#print axioms IUT.rabs_geom_sub_limit
#print axioms IUT.qFrac_mul_le
#print axioms IUT.geom_converges_to_limit
#print axioms IUT.geom_limit_object
#print axioms IUT.geomLimitData
#print axioms IUT.geomLimit_exists
#print axioms IUT.oneMinus_lower
#print axioms IUT.oneMinus_isPos
#print axioms IUT.Lbound
#print axioms IUT.geom_converges_self_contained
#print axioms IUT.geomConvergeSCData
#print axioms IUT.geomConvergeSC_exists
#print axioms IUT.stabHom_injective
#print axioms IUT.closureHom_surjective
#print axioms IUT.connected_dominated_by_galois
#print axioms IUT.orbit_dominated_by_galois
#print axioms IUT.closureTower_dominates
#print axioms IUT.galoisClosureLift_exists
#print axioms IUT.eis_coord_depth
#print axioms IUT.eis_separated
#print axioms IUT.eis_step_faithful
#print axioms IUT.eisSeparationData
#print axioms IUT.eisSeparation_exists
#print axioms IUT.SpanIso
#print axioms IUT.SpanIso.trans
#print axioms IUT.QuotientData.abstract_ess_surj_transitive
#print axioms IUT.QuotientData.abstract_ess_surj_orbit
#print axioms IUT.abstractEssSurjWitness
#print axioms IUT.abstractEssSurj_exists
#print axioms IUT.mu_pm_orbit_iff
#print axioms IUT.centerToMu_neg_inv
#print axioms IUT.mu_theta_labels
#print axioms IUT.theta_pm_mu_label
#print axioms IUT.muLIdentificationData
#print axioms IUT.muLIdentification_exists
#print axioms IUT.rabs_sub_pointwise
#print axioms IUT.geom_seq_isCauchy
#print axioms IUT.geom_rlim_complete
#print axioms IUT.geomRlimData
#print axioms IUT.geomRlim_exists
#print axioms IUT.SpanIso.sum
#print axioms IUT.SumData.hom_sum_spanIso
#print axioms IUT.SumData.abstract_ess_surj_finite
#print axioms IUT.SumData.abstract_ess_surj_orbits
#print axioms IUT.abstractEssSurjSum_exists
#print axioms IUT.funeqTwist_closed
#print axioms IUT.funeqTwist_mu
#print axioms IUT.thetaNegMod_section_twist
#print axioms IUT.funeq_heisenberg_mul
#print axioms IUT.thetaHeisenbergLift_exists
#print axioms IUT.boundedExponent_no_int_embedding
#print axioms IUT.tateCoverGrp_tempered
#print axioms IUT.tateCompletion_unique
#print axioms IUT.tateCompletion_deck_injective
#print axioms IUT.tateCoverGroup_exists
#print axioms IUT.GaloisCatData.powProj_fiber_surj
#print axioms IUT.GaloisCatData.sga1Point_exists
#print axioms IUT.abstract_connected_iff
#print axioms IUT.connected_dominated_by_galois_abstract
#print axioms IUT.abstractGaloisDomination_exists
#print axioms IUT.theta_refl_iter_label
#print axioms IUT.theta_refl_iter_series
#print axioms IUT.funeq_gauss_degree_twist
#print axioms IUT.funeq_analytic_group_bridge
#print axioms IUT.thetaFuneqBridge_exists
#print axioms IUT.muP1CyclicData
#print axioms IUT.muP1Cyclic_exists
#print axioms IUT.towerGen_val_exact
#print axioms IUT.towerGen_not_val_two
#print axioms IUT.lambdaTowerGen_exists
#print axioms IUT.essSurjCapstoneData
#print axioms IUT.essSurjCapstone_exists
#print axioms IUT.sumCover
#print axioms IUT.cover_fiber_faithful
#print axioms IUT.cover_deck_profinite_compat
#print axioms IUT.tateCoverCat_exists
#print axioms IUT.monoThetaEnv
#print axioms IUT.monoThetaEnv_exists
#print axioms IUT.convergenceProgram_exists
#print axioms IUT.imageCover
#print axioms IUT.tateGaloisData
#print axioms IUT.tateGaloisData_faithful
#print axioms IUT.tateCoverGalois_exists
#print axioms IUT.recInertia_teich_eq
#print axioms IUT.recRamSurj_covers
#print axioms IUT.recRamifiedSurj_exists
#print axioms IUT.theta_operator_hom
#print axioms IUT.theta_op_value_obstruction
#print axioms IUT.thetaOperatorHom_exists
#print axioms IUT.gaussLogShell_vol_wssq
#print axioms IUT.gaussLogShell_vol_lower
#print axioms IUT.logShell_exists
#print axioms IUT.tate_from_to
#print axioms IUT.tate_to_from
#print axioms IUT.tateFiberFunctor_exists
#print axioms IUT.upper_compat_not_symm
#print axioms IUT.ind311_refines
#print axioms IUT.indeterminacies_exists
#print axioms IUT.towerGen_transition_val
#print axioms IUT.lambdaTowerTrans_exists
#print axioms IUT.thetaChain_closure
#print axioms IUT.thetaChain_exists
#print axioms IUT.tateSurrogate_exists
#print axioms IUT.recUnram_covers
#print axioms IUT.recUnramified_exists
#print axioms IUT.thetaValExp_unique
#print axioms IUT.thetaValExp_orbit_mod
#print axioms IUT.thetaValueEval_exists
#print axioms IUT.logKummer_along_logPath
#print axioms IUT.logKummer_ind3_gated
#print axioms IUT.logKummer_exists
#print axioms IUT.formalEndRing
#print axioms IUT.oToEnd_surjective
#print axioms IUT.formalEndRing_exists
#print axioms IUT.cor312_of_311
#print axioms IUT.theorem311Rep_exists
#print axioms IUT.pillarDFoundation_exists
#print axioms IUT.theta_cong_dvd
#print axioms IUT.theta_label_injective
#print axioms IUT.thetaLabelInjective_exists
#print axioms IUT.towerGen_transition_pow_term_val_exact
#print axioms IUT.ringF_val_ge_two_iff_lin
#print axioms IUT.lambdaTowerExactVal_exists
#print axioms IUT.GaloisTower.colimEval_injective
#print axioms IUT.proRepresentation_of_domination
#print axioms IUT.connected_proRepresented
#print axioms IUT.proRepresentable_exists
#print axioms IUT.cor312_of_input
#print axioms IUT.iut_localized
#print axioms IUT.rep_of_input
#print axioms IUT.multiradialInput_exists
#print axioms IUT.gaussPilot311
#print axioms IUT.cor312_of_gaussPilot311
#print axioms IUT.gaussPilot311_exists
#print axioms IUT.recJoint_covers
#print axioms IUT.recSurjective_exists
#print axioms IUT.thetaEval_exists
#print axioms IUT.GaloisTower.colimEval_natural
#print axioms IUT.GaloisTower.towerComparison_faithful
#print axioms IUT.galoisEquivalence_exists
#print axioms IUT.pillarDInterface_exists
#print axioms IUT.formalGroupProgram_exists
#print axioms IUT.thetaValueConstruct_exists
#print axioms IUT.lambdaTowerRamif_exists
#print axioms IUT.galoisFullness_exists
#print axioms IUT.galoisEquivalenceFull_exists
#print axioms IUT.lambdaTowerExactRamif_exists
#print axioms IUT.towerGen_transition_val_exact_of_pi
#print axioms IUT.iut_localized_iff
#print axioms IUT.inputConverse_exists
#print axioms IUT.realMultiradialInput_exists
#print axioms IUT.iut_localized_real
#print axioms IUT.catEquivOfQuasiInverse
#print axioms IUT.catEquiv_reconstructed
#print axioms IUT.towerComparison_catEquiv_of_quasiInverse
#print axioms IUT.pillarDBetaLocalization_exists
#print axioms IUT.formalGroupPointLaws_exists
#print axioms IUT.thetaRingObject_exists
#print axioms IUT.thetaValMonomial_mul
#print axioms IUT.frobVol_wellDefined
#print axioms IUT.degZ_mono
#print axioms IUT.towerComparison_catEquiv_regular_nonempty
#print axioms IUT.thetaValueSubgroup_exists
#print axioms IUT.thetaValProd_eq_uMonHom
#print axioms IUT.nnqToQHom_exists
#print axioms IUT.nnqToQ_add
#print axioms IUT.lambdaTowerPiValBound_exists
#print axioms IUT.towerGen_transition_val_exact_uncond
#print axioms IUT.constTower_full_connected
#print axioms IUT.constTower_orbitGenerated_connected
#print axioms IUT.arithPilot_wellDefined
#print axioms IUT.arithSkeleton_cor312_iff
#print axioms IUT.lambdaTowerRamifCapstone_exists
#print axioms IUT.tower_pi_val_geom
#print axioms IUT.lambdaTowerPiValGeom_exists
#print axioms IUT.rlogVol_effmono
#print axioms IUT.logVolEffMono_exists
#print axioms IUT.thetaValueProdLaw_exists
#print axioms IUT.thetaValProd_append
#print axioms IUT.indAction_wellDefined
#print axioms IUT.unitIndAction_orbit
#print axioms IUT.thetaValueAlgebra_exists
#print axioms IUT.input_of_transport
#print axioms IUT.cor312_of_transport
#print axioms IUT.formalGroupPointOAction_exists
#print axioms IUT.lt_point_scalar_mul
#print axioms IUT.towerResidueSurj_exists
#print axioms IUT.tower_res_surjective
#print axioms IUT.connectedFullness_regTerminal_full
#print axioms IUT.gsetHquot_of_fiberTransitive
#print axioms IUT.thetaValueProdSwapAt_exists
#print axioms IUT.thetaValProd_swap_at
#print axioms IUT.connectedFullness_coreCover_full
#print axioms IUT.intermediateNormalCover_hfib
#print axioms IUT.formalGroupPointODerived_exists
#print axioms IUT.lt_point_scalar_comm
#print axioms IUT.towerRamifResidueKernel_exists
#print axioms IUT.tower_res_kills_val_ge_one
#print axioms IUT.transportDeg_iff_cor312
#print axioms IUT.transport_strictly_stronger
#print axioms IUT.arith_mirror_independent
#print axioms IUT.transportMirror
#print axioms IUT.thetaValueProdBlockSwap_exists
#print axioms IUT.thetaValProd_block_swap
#print axioms IUT.formalGroupOModulePoint_exists
#print axioms IUT.lt_point_scalar_assoc
#print axioms IUT.eisResidueFieldIso_exists
#print axioms IUT.eisRes_ker_eq_lambda
#print axioms IUT.normalPair_hfib_iff_normalizesSub
#print axioms IUT.normalPair_hquot
#print axioms IUT.indActionLabel_wellDefined
#print axioms IUT.degZ_swap
#print axioms IUT.pillarAFullnessProgram_exists
#print axioms IUT.thetaValueProdRangeSplit_exists
#print axioms IUT.thetaValProd_labelUpto_split
#print axioms IUT.fullIndActionFull_wellDefined
#print axioms IUT.full_indeterminacies_act
#print axioms IUT.nnqOrder_exists
#print axioms IUT.nnqToQ_mono
#print axioms IUT.towerResidueFieldIsoTower_exists
#print axioms IUT.tower_res_ker_eq_gen
#print axioms IUT.iutField_exists
#print axioms IUT.ratIUTField
#print axioms IUT.firstIsomorphism_exists
#print axioms IUT.quotientGroupN_exists
#print axioms IUT.profiniteTopology_exists
#print axioms IUT.subgroup_isOpen_iff_contains_kernel
#print axioms IUT.polyDivField_exists
#print axioms IUT.field_division_exists_unique
#print axioms IUT.fracField_exists
#print axioms IUT.Qp_is_field
#print axioms IUT.galoisGroup_exists
#print axioms IUT.fieldAutGroup_exists
#print axioms IUT.separable_exists
#print axioms IUT.finiteEtale_exists
#print axioms IUT.finiteEtale_exists_rat
#print axioms IUT.minPoly_exists
#print axioms IUT.simpleExt_field
#print axioms IUT.simpleExt_exists
#print axioms IUT.fiberFunctor_exists
#print axioms IUT.evalHom_isRingHom
#print axioms IUT.evalHom_exists
#print axioms IUT.rootAdj_is_root
#print axioms IUT.rootAdj_field_exists
#print axioms IUT.piEt_exists
#print axioms IUT.grothendieckGalois_exists
#print axioms IUT.algTensor_idem_complete
#print axioms IUT.algTensor_exists
#print axioms IUT.idemSpec_split_components
#print axioms IUT.idemSpec_exists
#print axioms IUT.galCorr_galois_connection
#print axioms IUT.galCorr_exists
#print axioms IUT.sepEmb_card_eq_degree
#print axioms IUT.sepEmb_card_eq_sepDegree
#print axioms IUT.towerLaw_degree_mul
#print axioms IUT.towerLaw_exists
#print axioms IUT.connEt_exists
#print axioms IUT.connEt_nontrivial_action_exists
#print axioms IUT.profPi1_exists
#print axioms IUT.profPi1_is_profinite
#print axioms IUT.normSplit_splits
#print axioms IUT.normSplit_normal_exists
#print axioms IUT.galPi1_iso
#print axioms IUT.galPi1_monodromy_full_exists
#print axioms IUT.galFund_fixing_fixed_eq
#print axioms IUT.galFund_main
#print axioms IUT.primEl_two_gen
#print axioms IUT.primEl_theorem
#print axioms IUT.specFun_map_comp
#print axioms IUT.specFun_exists
#print axioms IUT.zarConn_idem_clopen
#print axioms IUT.zarConn_iff_idem
#print axioms IUT.primeSpec_D_mul
#print axioms IUT.primeSpec_field_point
#print axioms IUT.ringLoc_universal
#print axioms IUT.ringLocRf_f_unit
#print axioms IUT.structSheaf_restrict_comp
#print axioms IUT.structSheaf_global_eq_ring
#print axioms IUT.fpts_ker_prime
#print axioms IUT.fpts_kpoint_is_hom
#print axioms IUT.globSec_recover_ring
#print axioms IUT.globSec_recover_hom
#print axioms IUT.locStalk_isLocal
#print axioms IUT.locStalk_stalk_is_local
#print axioms IUT.resField_quot_isField
#print axioms IUT.resField_of_maximal
#print axioms IUT.nilRad_quot_reduced
#print axioms IUT.nilRad_exists
#print axioms IUT.affEq_fully_faithful
#print axioms IUT.affEq_hom_iso
#print axioms IUT.intExt_scalar_integral
#print axioms IUT.intExt_field_integrallyClosed
#print axioms IUT.fracId_principal_is_invertible
#print axioms IUT.fracId_mul_monoid
#print axioms IUT.ringInt_Q_eq_Z_forward
#print axioms IUT.ringInt_exists
#print axioms IUT.valRing_isSubring
#print axioms IUT.valRing_is_local
#print axioms IUT.dedek_prime_residue_field
#print axioms IUT.dedek_exists
#print axioms IUT.locComp_hensel_step
#print axioms IUT.locComp_exists
#print axioms IUT.ellCurve_neg_on_curve
#print axioms IUT.ellCurve_exists
#print axioms IUT.etThReal_theta_vanish
#print axioms IUT.etThReal_exists
#print axioms IUT.picDiv_principal_isHom
#print axioms IUT.picDiv_exists
#print axioms IUT.ellJ_iso_invariant
#print axioms IUT.ellJ_exists
#print axioms IUT.thJac_quasi_period2
#print axioms IUT.thJac_exists
#print axioms IUT.logVol_degree_isHom
#print axioms IUT.logVol_effective_nonneg
#print axioms IUT.tate_point_period
#print axioms IUT.tateCurve_exists
#print axioms IUT.locRing_completion_isCRing
#print axioms IUT.locRing_embed_isHom
#print axioms IUT.logArch_vol_isHom
#print axioms IUT.logArch_global_complete
#print axioms IUT.tateTor_mu_in_torsion
#print axioms IUT.tateTor_exists
#print axioms IUT.algClo_exists
#print axioms IUT.algClo_absGalois_isProfinite
#print axioms IUT.fldComp_completion_isField
#print axioms IUT.fldComp_mul_inv_cancel_gen
#print axioms IUT.thLtor_torsion_lpow
#print axioms IUT.thLtor_exists
#print axioms IUT.thPilot_total_closed
#print axioms IUT.thPilot_cubic_bound
#print axioms IUT.kummer_cocycle
#print axioms IUT.kummer_quotient_group
#print axioms IUT.mThRig_constMult_rigid
#print axioms IUT.mThRig_exists
#print axioms IUT.logShell_smul_mem
#print axioms IUT.logShellReal_exists
#print axioms IUT.cycRig_char_isHom
#print axioms IUT.cycRig_rigidity
#print axioms IUT.absTop_add_from_one_add
#print axioms IUT.absTop_add_from_mult
#print axioms IUT.gPilot_theorem311_conditional
#print axioms IUT.gPilot_crux_is_hypothesis
#print axioms IUT.logKum_frob_etale
#print axioms IUT.logKum_commute
#print axioms IUT.thLink_map_eq_qparam
#print axioms IUT.thLink_crux_stage
#print axioms IUT.galH1_quotient_isGroup
#print axioms IUT.galH1_trivial_action
#print axioms IUT.absF_add_eq
#print axioms IUT.absF_absTopIII
#print axioms IUT.locRec_isHom
#print axioms IUT.locRec_prime_frob
#print axioms IUT.frobC_is_category
#print axioms IUT.frobC_degree_mult
#print axioms IUT.indR_ind1_invariant
#print axioms IUT.indR_multiradial_seed
#print axioms IUT.discRig_period_exponent_isZ
#print axioms IUT.discRig_rigidity
#print axioms IUT.logLink_hom
#print axioms IUT.logLink_exists
#print axioms IUT.cycRec_mu_from_chi
#print axioms IUT.cycRec_absTopIII_cyclotome
#print axioms IUT.normG_isHom
#print axioms IUT.normG_artin_kernel_link
#print axioms IUT.thCyc_rigIso_faithful
#print axioms IUT.thCyc_three_rigidities
#print axioms IUT.haar_additive
#print axioms IUT.haar_ball_closed
#print axioms IUT.mlv_additive
#print axioms IUT.mlv_from_measure
#print axioms IUT.hil90_theorem
#print axioms IUT.hil90_H1_trivial
#print axioms IUT.indF_simultaneous_real
#print axioms IUT.indF_crux_is_hypothesis
#print axioms IUT.weil_bilinear_left
#print axioms IUT.weil_nondegenerate
#print axioms IUT.galTh_equivariant
#print axioms IUT.galTh_norm_qpower
#print axioms IUT.cruxR_is_hypothesis
#print axioms IUT.cruxR_mirror
#print axioms IUT.tmt_act_transitive
#print axioms IUT.tmt_norm_qpower
#print axioms IUT.wge_equivariant
#print axioms IUT.kex_iso_injective
#print axioms IUT.arch_scaling
#print axioms IUT.arch_logvol_scaling
#print axioms IUT.szp_cor312_implies_szpiro
#print axioms IUT.szp_full_chain
#print axioms IUT.pf_product_formula
#print axioms IUT.pf_degree_hom
#print axioms IUT.kcr_cocycle
#print axioms IUT.kcr_supplies_galTh
#print axioms IUT.tkc_is_cocycle
#print axioms IUT.tkc_class_well_defined
#print axioms IUT.cup_cocycle
#print axioms IUT.cup_coboundary
#print axioms IUT.tkr_class_rigid
#print axioms IUT.tkr_no_cyclotomic_indeterminacy
#print axioms IUT.wkd_dual_injective
#print axioms IUT.wkd_kummer_compat
#print axioms IUT.ard_deg_hom
#print axioms IUT.ard_principal_degree_zero
#print axioms IUT.abc_fermat_exponent_bounded
#print axioms IUT.abc_full_chain
#print axioms IUT.cgc_graded_comm
#print axioms IUT.cgc_supplies_hypothesis
#print axioms IUT.fab_degrees_agree
#print axioms IUT.fab_deg_additive
#print axioms IUT.brau_is_abelian
#print axioms IUT.brau_split_iff
#print axioms IUT.mrc_compare_iso
#print axioms IUT.mrc_multiradial_seed
#print axioms IUT.mte_capstone
#print axioms IUT.mte_coherent
#print axioms IUT.atm_absTopII
#print axioms IUT.atm_units_is_group
#print axioms IUT.qpf_product_formula
#print axioms IUT.qpf_reduce_to_Q
#print axioms IUT.lli_commute_general
#print axioms IUT.lli_ind3_shift
#print axioms IUT.tgo_galois_orbit_permuted
#print axioms IUT.tgo_orbit_finite
#print axioms IUT.bri_inv_hom
#print axioms IUT.bri_supplies_hypothesis
#print axioms IUT.tmp_extension_exact
#print axioms IUT.tmp_discrete_vs_profinite
#print axioms IUT.mrp_well_defined
#print axioms IUT.mrp_multiradial
#print axioms IUT.tcv_covering_exact
#print axioms IUT.tcv_tempered_kills_profinite
#print axioms IUT.hsym_bilinear_left
#print axioms IUT.hsym_antisymmetric
#print axioms IUT.dsc_ramified_two
#print axioms IUT.dsc_split_degree_sum
#print axioms IUT.top_product_galois_fixed
#print axioms IUT.top_cyc_prod_pow
#print axioms IUT.tpb_orbit_exp_eq_pilot_core
#print axioms IUT.tpb_pilot_volume_of_orbit
#print axioms IUT.cyd_ramified_iff
#print axioms IUT.cyd_p_totally_ramified
#print axioms IUT.lkm_rep_preserved
#print axioms IUT.lkm_kummer_class_transported
#print axioms IUT.tsy_tame_antisymmetric
#print axioms IUT.tsy_concrete_invariant
#print axioms IUT.ttw_tower_compat
#print axioms IUT.ttw_discrete_complete_injective
#print axioms IUT.cdf_cond_disc_formula
#print axioms IUT.cdf_tamely_ramified
#print axioms IUT.tcm_deck_commutator_trivial
#print axioms IUT.tcm_action_commutes
#print axioms IUT.trb_env_meet
#print axioms IUT.trb_exists
#print axioms IUT.mind_comp_invariant
#print axioms IUT.mind_exists
#print axioms IUT.ltm_exists
#print axioms IUT.ltmFuncEq
#print axioms IUT.cpp_different_eq_wild_formula
#print axioms IUT.cpp_wildly_ramified
#print axioms IUT.ttc_commutator_mu
#print axioms IUT.ttc_thetaGrp_not_tcmAbelian
#print axioms IUT.ltr_rec_inverse
#print axioms IUT.ltr_exists
#print axioms IUT.lsc_log_upper
#print axioms IUT.lsc_graded_iso
#print axioms IUT.mtt_triple_holds
#print axioms IUT.mtt_zeta_sq_mul
#print axioms IUT.llsc_graded_iso
#print axioms IUT.llsc_vol_upper_compat
#print axioms IUT.tktb_class_governed
#print axioms IUT.tktb_exists
#print axioms IUT.ltng_kernel_eq_norm
#print axioms IUT.ltng_exists
#print axioms IUT.cda_cond_disc_formula
#print axioms IUT.cda_specialize_M381F
#print axioms IUT.ttoa_commutator_twist
#print axioms IUT.ttoa_exists
#print axioms IUT.tvtb_class_value
#print axioms IUT.tvtb_exists
#print axioms IUT.tgr_central_iff
#print axioms IUT.tgr_exists
#print axioms IUT.rid_disc_eq_norm_different
#print axioms IUT.rid_specialize_cpp
#print axioms IUT.ltls_square_commutes
#print axioms IUT.ltls_exists
#print axioms IUT.brf_inv_injective_subgroup
#print axioms IUT.brf_exists
#print axioms IUT.tvob_orbit_exponent
#print axioms IUT.tvob_exists
#print axioms IUT.rbc_inv_eq_char_rec
#print axioms IUT.rbc_exists
#print axioms IUT.mlc_compare_around_square
#print axioms IUT.mlc_exists
#print axioms IUT.dlb_disc_gt_one
#print axioms IUT.dlb_exists
#print axioms IUT.tgrig_rigidity
#print axioms IUT.tgrig_cyclotome_rigid
#print axioms IUT.topb_orbit_sum
#print axioms IUT.topb_exists
#print axioms IUT.tlm_thetaLink_rep_square
#print axioms IUT.tlm_exists
#print axioms IUT.cgm_inner_galois_commute
#print axioms IUT.cgm_exists
#print axioms IUT.rnd_left_nondegenerate
#print axioms IUT.rnd_exists
#print axioms IUT.icg_class_trivial_iff_principal
#print axioms IUT.icg_exists
#print axioms IUT.tovb_orbit_volume
#print axioms IUT.tovb_exists
#print axioms IUT.atfc_absTopIII_from_cyclotome
#print axioms IUT.atfc_exists
#print axioms IUT.pcm_multiradial_crux_iff
#print axioms IUT.pcm_exists
#print axioms IUT.fr_degree_transform
#print axioms IUT.fr_exists
#print axioms IUT.hsr_symbol_vanishes_iff_norm
#print axioms IUT.hsr_exists
#print axioms IUT.tpgb_pilot_cores
#print axioms IUT.tpgb_exists
#print axioms IUT.atfull_absTopI_II_III
#print axioms IUT.atfull_exists
#print axioms IUT.fld_exists
#print axioms IUT.lpb_exists
#print axioms IUT.huf_norm_map_level
#print axioms IUT.huf_exists
#print axioms IUT.mtk_class_transport
#print axioms IUT.mtk_exists
#print axioms IUT.rnf_norm_shift
#print axioms IUT.rnf_exists
#print axioms IUT.cnf_reduction
#print axioms IUT.cnf_exists
#print axioms IUT.krf_kappa_map_mul
#print axioms IUT.krf_exists
#print axioms IUT.pvu_upper_containment
#print axioms IUT.pvu_exists
#print axioms IUT.tcvb_exp_from_commutator
#print axioms IUT.tcvb_exists
#print axioms IUT.dff_sum_eq
#print axioms IUT.dff_exists
#print axioms IUT.pbm_crux_within_two_sided
#print axioms IUT.pbm_exists
#print axioms IUT.acd_pic0_iff_deg_zero
#print axioms IUT.acd_exists
#print axioms IUT.tpe_extension_exact
#print axioms IUT.tpe_commutator_cyclotome
#print axioms IUT.tpe_act_commutator_twist
#print axioms IUT.tpe_exists
#print axioms IUT.arc_sum_eq_num
#print axioms IUT.arc_exists
#print axioms IUT.tccb_commutator_class
#print axioms IUT.tccb_exists
EOF
lake env lean /tmp/iut_check_axioms.lean

echo "OK: all theorems verified, no sorry."
echo "Expected: standard axioms only. mono_implies_bi is axiom-free;"
echo "bi_implies_mono_classical requires Classical.choice (the point of M1-2)."
