#!/usr/bin/env bash
# IUT 系3.12 形式検証のビルド + 公理チェック
# 必要: elan (https://github.com/leanprover/elan)
set -euo pipefail
cd "$(dirname "$0")"

lake build

# sorry や追加公理に依存していないことを確認
cat > /tmp/iut_check_axioms.lean <<'EOF'
import IUT
#print axioms IUT.verdict
#print axioms IUT.ss_incompatible
#print axioms IUT.cor312_independent
#print axioms IUT.controversy_reduces_to_rc
#print axioms IUT.mono_implies_bi
#print axioms IUT.bi_implies_mono_classical
#print axioms IUT.AddSym.act_comp
#print axioms IUT.theta_labels
#print axioms IUT.path_col
#print axioms IUT.cross_col_needs_theta
#print axioms IUT.abc_implies_asymptotic_fermat
#print axioms IUT.szpiro_of_cor312
#print axioms IUT.szpiro_of_cor312_precise
#print axioms IUT.cor312_of_multiradial
#print axioms IUT.strict_evaluation_obstruction
#print axioms IUT.padding_necessary
#print axioms IUT.multiradial_consistent
#print axioms IUT.gaussian_obstruction
#print axioms IUT.szpiro_of_multiradial
#print axioms IUT.recon_log_compat
#print axioms IUT.addSym_inverse
#print axioms IUT.bicoric_constant
#print axioms IUT.theta_value_pm_symmetry
#print axioms IUT.two_mul_procTotal
#print axioms IUT.height_bounded_of_uniform_szpiro
#print axioms IUT.abc_bounds_catalan23
#print axioms IUT.six_mul_sumSq
#print axioms IUT.invariant_transport
#print axioms IUT.geometric_normal
#print axioms IUT.outer_conjugation_unique
#print axioms IUT.outer_action_inner_on_kernel
#print axioms IUT.slim_faithful
#print axioms IUT.section_decomposition
#print axioms IUT.theta_deck_not_finite
#print axioms IUT.theta_exponent_unique
#print axioms IUT.theta_exponent_not_periodic
#print axioms IUT.finite_quotient_collapses_theta
#print axioms IUT.arithmetic_quotient_collapses_theta
#print axioms IUT.temperedArithmetic_consistent
#print axioms IUT.tempered_invariant_transport
#print axioms IUT.findWitness_spec
#print axioms IUT.abelianization_determines
#print axioms IUT.reconCore_correct
#print axioms IUT.padic_recon_monoanabelian
#print axioms IUT.padic_recon_bianabelian
#print axioms IUT.padic_invariant_transport
#print axioms IUT.cyclotome_indeterminacy
#print axioms IUT.marked_cyclotome_rigid
#print axioms IUT.theta_comm
#print axioms IUT.mono_theta_cyclotomic_rigidity
#print axioms IUT.rigid_theta_values
#print axioms IUT.Frobenioid.deg_zero
#print axioms IUT.frob_not_invertible
#print axioms IUT.gaussianDiv_deg
#print axioms IUT.frobenioid_realizes_qpilot
#print axioms IUT.degree_volume_consistent
#print axioms IUT.GrpCong.inv_compat
#print axioms IUT.quot_exact
#print axioms IUT.quot_universal
#print axioms IUT.limit_universal
#print axioms IUT.toZhat_injective
#print axioms IUT.zmod_bounded_exponent
#print axioms IUT.zmod_collapses_theta
#print axioms IUT.equivariant_is_right_mul
#print axioms IUT.fiber_functor_recovers_group
#print axioms IUT.level_transition_equivariant
#print axioms IUT.galois_closure
#print axioms IUT.genOpen_minimal
#print axioms IUT.continuous_into_gen
#print axioms IUT.limitProj_continuous
#print axioms IUT.limit_mul_continuous
#print axioms IUT.limit_inv_continuous
#print axioms IUT.projKernel_isOpen
#print axioms IUT.cylinder_nbhd_basis
#print axioms IUT.projKernel_nbhd
#print axioms IUT.zhat_proj_surjective
#print axioms IUT.cosetAction
#print axioms IUT.orbit_stabilizer
#print axioms IUT.orbit_transitive
#print axioms IUT.every_orbit_is_coset
#print axioms IUT.coset_hom_iff
#print axioms IUT.levelAction_smooth
#print axioms IUT.levelAction_stabilizer_open
#print axioms IUT.pigeonhole
#print axioms IUT.card_unique
#print axioms IUT.finite_bounded_exponent
#print axioms IUT.zmod_finite
#print axioms IUT.zmod_listable
#print axioms IUT.listable_discrete_compact
#print axioms IUT.zmod_compact
#print axioms IUT.compact_image
#print axioms IUT.compact_prod
#print axioms IUT.restrictEquiv
#print axioms IUT.skel_classification
#print axioms IUT.fiberAut
#print axioms IUT.from_to
#print axioms IUT.to_from
#print axioms IUT.sga1Equivalence
#print axioms IUT.gsets_G1_final
#print axioms IUT.gsets_G1_pullback
#print axioms IUT.gsets_G2_initial
#print axioms IUT.gsets_G2_sum
#print axioms IUT.gsets_G3_factorization
#print axioms IUT.gsets_G4_forgetful_preserves_pullback
#print axioms IUT.gsets_G5_forgetful_preserves_sum
#print axioms IUT.gsets_G6_reflects_iso
#print axioms IUT.GaloisCatData.eq_mono
#print axioms IUT.GaloisCatData.feq_surj
#print axioms IUT.GaloisCatData.fiber_faithful
#print axioms IUT.GaloisCatData.mono_of_fiber_injective
#print axioms IUT.GaloisCatData.evaluation_injective
#print axioms IUT.GaloisCatData.galois_evaluation_bijective
#print axioms IUT.gsetGaloisData
#print axioms IUT.galoisCatData_consistent
#print axioms IUT.CatIso.ext
#print axioms IUT.GaloisCatData.autGrp
#print axioms IUT.GaloisCatData.homFunctor
#print axioms IUT.GaloisCatData.homFunctor_faithful
#print axioms IUT.GaloisCatData.connected_hom_surjective
#print axioms IUT.GaloisCatData.split_connected_transitive
#print axioms IUT.DescentData.homFunctor_full
#print axioms IUT.DescentData.sga1_fully_faithful
#print axioms IUT.gsetDescentData
#print axioms IUT.descentData_consistent
#print axioms IUT.Grp.mul_inv_cancel_left
#print axioms IUT.QuotientData.quotient_realizes_coset
#print axioms IUT.QuotientData.sga1_essentially_surjective
#print axioms IUT.gsetQuotientData
#print axioms IUT.quotientData_consistent
#print axioms IUT.GaloisCatData.aut_transition_exists_unique
#print axioms IUT.GaloisCatData.aut_transition_surjective
#print axioms IUT.GaloisTower.transAut_mul
#print axioms IUT.GaloisTower.towerSystem
#print axioms IUT.GaloisTower.pi1Tower
#print axioms IUT.GaloisTower.pi1Tower_mul_continuous
#print axioms IUT.unitAction_galois
#print axioms IUT.galoisTower_consistent
#print axioms IUT.assemble_level
#print axioms IUT.refine_step
#print axioms IUT.natSystem_compact
#print axioms IUT.pi1Tower_compact
#print axioms IUT.factChain_compact
#print axioms IUT.SumData.connected_factors
#print axioms IUT.SumData.hom_sum_realizes
#print axioms IUT.SumData.sum_decomposition
#print axioms IUT.gsetSumData
#print axioms IUT.sumData_consistent
#print axioms IUT.Zp
#print axioms IUT.Zp_compact
#print axioms IUT.Zp_mul_continuous
#print axioms IUT.toZp_injective
#print axioms IUT.unramifiedRec
#print axioms IUT.unramifiedRec_kernel
#print axioms IUT.unramifiedRec_level_surj
#print axioms IUT.unramifiedLocalCFT
#print axioms IUT.localCFT_consistent
#print axioms IUT.map_le_iff_le_comap
#print axioms IUT.comap_map_of_injective
#print axioms IUT.norm_correspondence
#print axioms IUT.unramified_norm_correspondence
#print axioms IUT.dvd_sub_mul
#print axioms IUT.zpMul
#print axioms IUT.zpMul_comm
#print axioms IUT.geom_identity
#print axioms IUT.zmod_principal_unit_invertible
#print axioms IUT.dvd_sub_geomSum
#print axioms IUT.geomSum_levels
#print axioms IUT.isPrincipalUnit_mul
#print axioms IUT.zpGeomInv
#print axioms IUT.principalUnits
#print axioms IUT.principalUnits_comm
#print axioms IUT.principal_unit_invertible
#print axioms IUT.toZp_one_add_principal
#print axioms IUT.unitFiltration
#print axioms IUT.unitFiltration_full
#print axioms IUT.unitFiltration_antitone
#print axioms IUT.unitFiltration_separated
#print axioms IUT.levelTheta
#print axioms IUT.unitTheta_hom
#print axioms IUT.unitTheta_kernel
#print axioms IUT.unitTheta_surj
#print axioms IUT.succ_mul_chs
#print axioms IUT.bezout
#print axioms IUT.euclid
#print axioms IUT.isPrime_two
#print axioms IUT.isPrime_three
#print axioms IUT.prime_dvd_chs
#print axioms IUT.binomial
#print axioms IUT.freshman
#print axioms IUT.fermat_little
#print axioms IUT.pow_sub_factor
#print axioms IUT.pow_lift
#print axioms IUT.teich_step
#print axioms IUT.teich
#print axioms IUT.teich_reduction
#print axioms IUT.teich_mul
#print axioms IUT.teich_one
#print axioms IUT.teich_frobenius
#print axioms IUT.zpPow
#print axioms IUT.zpPow_succ
#print axioms IUT.euclid_int
#print axioms IUT.flt_unit
#print axioms IUT.euler_pow
#print axioms IUT.teich_root_of_unity
#print axioms IUT.teich_invertible
#print axioms IUT.zpMul_assoc
#print axioms IUT.zpOne_mul
#print axioms IUT.isPrincipalUnit_of_level_one
#print axioms IUT.teich_congr
#print axioms IUT.unit_decomposition
#print axioms IUT.decomposition_unique
#print axioms IUT.not_dvd_ipow
#print axioms IUT.isZpUnit_mul
#print axioms IUT.isZpUnit_teich
#print axioms IUT.isZpUnit_of_principal
#print axioms IUT.unit_pow_principal
#print axioms IUT.zpUnitInv_mul
#print axioms IUT.zpUnits
#print axioms IUT.zpUnits_comm
#print axioms IUT.zpUnits_decomposition
#print axioms IUT.prodHom_injective
#print axioms IUT.recQp
#print axioms IUT.recQp_injective
#print axioms IUT.recQp_units_to_inertia
#print axioms IUT.fullLocalCFT
#print axioms IUT.fullLocalCFT_consistent
#print axioms IUT.CRing.right_distrib
#print axioms IUT.CRing.mul_zero
#print axioms IUT.CRing.toGrp
#print axioms IUT.intRing
#print axioms IUT.zmodRing
#print axioms IUT.zpRing
#print axioms IUT.toZpRing
#print axioms IUT.projRing
#print axioms IUT.rsum_add
#print axioms IUT.rsum_reflect
#print axioms IUT.rsum_triangle
#print axioms IUT.psRing
#print axioms IUT.psConstHom
#print axioms IUT.rsum_single
#print axioms IUT.psPow_add
#print axioms IUT.psPow_coeff_zero
#print axioms IUT.psComp_add
#print axioms IUT.psComp_one
#print axioms IUT.psComp_X
#print axioms IUT.psComp_coeff_zero
#print axioms IUT.psComp_coeff_one
#print axioms IUT.CRing.add_quad_swap
#print axioms IUT.psPow_congr
#print axioms IUT.psPow_coeff_diag
#print axioms IUT.psPow_coeff_congr
#print axioms IUT.lubin_tate_unique
#print axioms IUT.CRing.cancel_to_annihilate
#print axioms IUT.zp_p_regular
#print axioms IUT.zp_unit_regular
#print axioms IUT.zp_lt_cancel
#print axioms IUT.lubin_tate_unique_zp
#print axioms IUT.zpDivP
#print axioms IUT.zpDivP_mul_cancel
#print axioms IUT.zpDivP_cancel
#print axioms IUT.zp_dvd_p_iff
#print axioms IUT.zp_flt
#print axioms IUT.zp_frobenius_divisible
#print axioms IUT.rofNat_add
#print axioms IUT.rofNat_mul
#print axioms IUT.binomial2
#print axioms IUT.rofNat_chs_factor
#print axioms IUT.freshman_ring
#print axioms IUT.freshman_ps
#print axioms IUT.psC_mul_coeff
#print axioms IUT.rofNat_zp
#print axioms IUT.freshman_zp
EOF
lake env lean /tmp/iut_check_axioms.lean

echo "OK: all theorems verified, no sorry."
echo "Expected: standard axioms only. mono_implies_bi is axiom-free;"
echo "bi_implies_mono_classical requires Classical.choice (the point of M1-2)."
