/-
  宇宙際タイヒミュラー論 (IUT) 系3.12 の形式検証

  teichmuller/pdf/ の原論文 6 本を一次資料として、
  系3.12 をめぐる論争の形式骨格を Lean 4 で構成・検証する。
-/
import IUT.Arithmetic
import IUT.Skeleton
import IUT.ScholzeStix
import IUT.Mochizuki
import IUT.Boolean
import IUT.Verdict
import IUT.Anabelian
import IUT.HodgeTheater
import IUT.LogThetaLattice
import IUT.AbcConsequences
import IUT.Diophantine
import IUT.Multiradial
import IUT.Evaluation
import IUT.FundamentalGroup
import IUT.Reconstruction
import IUT.EtaleTheta
import IUT.Frobenioid
import IUT.Profinite
import IUT.GaloisCategory
import IUT.Topology
import IUT.SGA1
import IUT.Finiteness
import IUT.Compactness
import IUT.CategoryTheory
import IUT.GaloisAxioms
import IUT.AbstractGalois
import IUT.SGA1Completion
import IUT.SGA1Object
import IUT.ProObject
import IUT.LimitCompact
import IUT.SumDecomposition
import IUT.LocalCFT
import IUT.NormCorrespondence
import IUT.PrincipalUnits
import IUT.PrincipalUnitGroup
import IUT.UnitFiltration
import IUT.Fermat
import IUT.Teichmuller
import IUT.RootsOfUnity
import IUT.UnitDecomposition
import IUT.ZpUnits
import IUT.FullReciprocity
import IUT.Ring
import IUT.PowerSeries
import IUT.Composition
import IUT.LubinTateUnique
import IUT.LubinTateZp
import IUT.PadicDivision
import IUT.ZpDomain
import IUT.Binomial2
import IUT.Freshman
import IUT.PSFunctor
import IUT.FrobeniusCharP
import IUT.LTErrorDivisible
import IUT.LubinTateExists
import IUT.FrobenioidCat
import IUT.FrobenioidModel
import IUT.PolyIsomorphism
import IUT.SplitFrobenioid
import IUT.FiberedFrobenioid
import IUT.SplitFibered
import IUT.RamifiedBase
import IUT.RamifiedSplit
import IUT.PowerSeries2
import IUT.FormalGroupSub
import IUT.FormalGroupEq
import IUT.FormalGroupMap
import IUT.FrobeniusGen
import IUT.Frobenius2
import IUT.FormalGroupErr
import IUT.FormalGroupCongr
import IUT.FormalGroupDecomp
import IUT.FormalGroupDiag
import IUT.FormalGroupExists
import IUT.FormalGroupUnique
import IUT.FormalGroupComm
import IUT.PowerSeries3
import IUT.FormalGroup3Congr
import IUT.FormalGroup3Decomp
import IUT.FormalGroup3Unique
import IUT.FormalGroupAssocDef
import IUT.FormalGroupChain
import IUT.FormalGroupFam
import IUT.FormalGroupMult
import IUT.FormalGroupComp1
import IUT.FormalGroupComp2
import IUT.FormalGroupBridge
import IUT.FormalGroupMult3
import IUT.FormalGroupLift
import IUT.FormalGroupComp3
import IUT.FormalGroupAssoc
import IUT.FormalGroupEval
import IUT.FormalGroupEvalMult
import IUT.FormalGroupEvalComp
import IUT.LTIterate
import IUT.FormalGroupInverse
import IUT.FormalGroupOModule
import IUT.FormalGroupInvLeft
import IUT.FormalGroupEnd
import IUT.FormalGroupPoints
import IUT.PointValues
import IUT.FormalGroupPointsMul
import IUT.FormalGroupPointsComp
import IUT.FormalGroupPoints2
import IUT.TorsionPoints
import IUT.TorsionTrivial
import IUT.EisensteinRing
import IUT.EisensteinTorsion
import IUT.EisensteinConjugates
import IUT.RamifiedEntrance
import IUT.EisensteinGalois
import IUT.RecRamified
import IUT.EisensteinTower
import IUT.EisensteinUpper
import IUT.EisDomain
import IUT.EisDomain2
import IUT.EisEndoRigidity
import IUT.FactorTheorem
import IUT.LambdaClassify
import IUT.LaurentCoeff
import IUT.LaurentRing
import IUT.LaurentMonomial
import IUT.ThetaSeries
import IUT.ThetaFunctional
import IUT.ThetaReflection
import IUT.ThetaGauss
import IUT.TateQuotient
import IUT.MonoThetaWitness
import IUT.ThetaGroupMod
import IUT.GaussianVolume
import IUT.RecGluing
import IUT.FormalGroupPointsLaw
import IUT.FormalGroupPoints3
import IUT.FormalGroupPointsMul2
import IUT.FormalGroupPointsMul3
import IUT.FormalGroupPointsAssoc
import IUT.Premises311
import IUT.VolumeModel
import IUT.DecompositionInertia
import IUT.Realification
import IUT.ArchimedeanPlace
import IUT.FormalGroupEndRing
import IUT.MuUnits
import IUT.ZmodOrder
import IUT.NatPrimeParts
import IUT.PrimitiveRoot
import IUT.CyclicUnits
import IUT.LambdaModule
import IUT.LambdaSemilinear
import IUT.RamifiedReciprocity
import IUT.FlUnits
import IUT.PadicSeries
import IUT.EisTowerRings
import IUT.FlStar
import IUT.PadicSeries2
import IUT.ResidueTower
import IUT.TowerTorsion
import IUT.TorsionResidue
import IUT.PadicGeometric
import IUT.ThetaPM
import IUT.Rationals
import IUT.FlStarCount
import IUT.ZpUnitDecomp
import IUT.RegularReal
import IUT.TowerNonzero
import IUT.RatFloor
import IUT.MuLSubgroup
import IUT.EisFaithful
import IUT.CyclotomicSync
import IUT.RealMul
import IUT.RealOrder
import IUT.ThetaCenterMod
import IUT.RealAbs
import IUT.RealComplete
import IUT.RealPosMul
import IUT.RealLe
import IUT.LogVolBridge
import IUT.VolumeReal
import IUT.GaussianDivisor
import IUT.Premises311Real
import IUT.WeightedGauss
import IUT.RealOrderComplete
import IUT.FuneqLift
import IUT.ScalarDistrib
import IUT.RealVolumeTheory
