/-
  宇宙際タイヒミュラー論 (IUT) 系3.12 の形式検証

  teichmuller/pdf/ の原論文 6 本を一次資料として、
  系3.12 をめぐる論争の形式骨格を Lean 4 で構成・検証する。
-/
import IUT.Arithmetic
import IUT.Skeleton
import IUT.ScholzeStix
import IUT.Mochizuki
import IUT.Boolean
import IUT.Verdict
import IUT.Anabelian
import IUT.HodgeTheater
import IUT.LogThetaLattice
import IUT.AbcConsequences
import IUT.Diophantine
import IUT.Multiradial
import IUT.Evaluation
import IUT.FundamentalGroup
import IUT.Reconstruction
import IUT.EtaleTheta
import IUT.Frobenioid
import IUT.Profinite
import IUT.GaloisCategory
import IUT.Topology
import IUT.SGA1
import IUT.Finiteness
import IUT.Compactness
import IUT.CategoryTheory
import IUT.GaloisAxioms
import IUT.AbstractGalois
import IUT.SGA1Completion
import IUT.SGA1Object
import IUT.ProObject
import IUT.LimitCompact
import IUT.SumDecomposition
import IUT.LocalCFT
import IUT.NormCorrespondence
import IUT.PrincipalUnits
import IUT.PrincipalUnitGroup
import IUT.UnitFiltration
import IUT.Fermat
import IUT.Teichmuller
import IUT.RootsOfUnity
import IUT.UnitDecomposition
import IUT.ZpUnits
import IUT.FullReciprocity
import IUT.Ring
import IUT.PowerSeries
import IUT.Composition
import IUT.LubinTateUnique
import IUT.LubinTateZp
import IUT.PadicDivision
import IUT.ZpDomain
import IUT.Binomial2
import IUT.Freshman
import IUT.PSFunctor
import IUT.FrobeniusCharP
import IUT.LTErrorDivisible
import IUT.LubinTateExists
import IUT.FrobenioidCat
import IUT.FrobenioidModel
import IUT.PolyIsomorphism
import IUT.SplitFrobenioid
import IUT.FiberedFrobenioid
import IUT.SplitFibered
import IUT.RamifiedBase
import IUT.RamifiedSplit
import IUT.PowerSeries2
import IUT.FormalGroupSub
import IUT.FormalGroupEq
import IUT.FormalGroupMap
import IUT.FrobeniusGen
import IUT.Frobenius2
import IUT.FormalGroupErr
import IUT.FormalGroupCongr
import IUT.FormalGroupDecomp
import IUT.FormalGroupDiag
import IUT.FormalGroupExists
import IUT.FormalGroupUnique
import IUT.FormalGroupComm
import IUT.PowerSeries3
import IUT.FormalGroup3Congr
import IUT.FormalGroup3Decomp
import IUT.FormalGroup3Unique
import IUT.FormalGroupAssocDef
import IUT.FormalGroupChain
import IUT.FormalGroupFam
import IUT.FormalGroupMult
import IUT.FormalGroupComp1
import IUT.FormalGroupComp2
import IUT.FormalGroupBridge
import IUT.FormalGroupMult3
import IUT.FormalGroupLift
import IUT.FormalGroupComp3
import IUT.FormalGroupAssoc
import IUT.FormalGroupEval
import IUT.FormalGroupEvalMult
import IUT.FormalGroupEvalComp
import IUT.LTIterate
import IUT.FormalGroupInverse
import IUT.FormalGroupOModule
import IUT.FormalGroupInvLeft
import IUT.FormalGroupEnd
import IUT.FormalGroupPoints
import IUT.PointValues
import IUT.FormalGroupPointsMul
import IUT.FormalGroupPointsComp
import IUT.FormalGroupPoints2
import IUT.TorsionPoints
import IUT.TorsionTrivial
import IUT.EisensteinRing
import IUT.EisensteinTorsion
import IUT.EisensteinConjugates
import IUT.RamifiedEntrance
import IUT.EisensteinGalois
import IUT.RecRamified
import IUT.EisensteinTower
import IUT.EisensteinUpper
import IUT.EisDomain
import IUT.EisDomain2
import IUT.EisEndoRigidity
import IUT.FactorTheorem
import IUT.LambdaClassify
import IUT.LaurentCoeff
import IUT.LaurentRing
import IUT.LaurentMonomial
import IUT.ThetaSeries
import IUT.ThetaFunctional
import IUT.ThetaReflection
import IUT.ThetaGauss
import IUT.TateQuotient
import IUT.MonoThetaWitness
import IUT.ThetaGroupMod
import IUT.GaussianVolume
import IUT.RecGluing
import IUT.FormalGroupPointsLaw
import IUT.FormalGroupPoints3
import IUT.FormalGroupPointsMul2
import IUT.FormalGroupPointsMul3
import IUT.FormalGroupPointsAssoc
import IUT.Premises311
import IUT.VolumeModel
import IUT.DecompositionInertia
import IUT.Realification
import IUT.ArchimedeanPlace
import IUT.FormalGroupEndRing
import IUT.MuUnits
import IUT.ZmodOrder
import IUT.NatPrimeParts
import IUT.PrimitiveRoot
import IUT.CyclicUnits
import IUT.LambdaModule
import IUT.LambdaSemilinear
import IUT.RamifiedReciprocity
import IUT.FlUnits
import IUT.PadicSeries
import IUT.EisTowerRings
import IUT.FlStar
import IUT.PadicSeries2
import IUT.ResidueTower
import IUT.TowerTorsion
import IUT.TorsionResidue
import IUT.PadicGeometric
import IUT.ThetaPM
import IUT.Rationals
import IUT.FlStarCount
import IUT.ZpUnitDecomp
import IUT.RegularReal
import IUT.TowerNonzero
import IUT.RatFloor
import IUT.MuLSubgroup
import IUT.EisFaithful
import IUT.CyclotomicSync
import IUT.RealMul
import IUT.RealOrder
import IUT.ThetaCenterMod
import IUT.RealAbs
import IUT.RealComplete
import IUT.RealPosMul
import IUT.RealLe
import IUT.LogVolBridge
import IUT.VolumeReal
import IUT.GaussianDivisor
import IUT.Premises311Real
import IUT.WeightedGauss
import IUT.RealOrderComplete
import IUT.FuneqLift
import IUT.ScalarDistrib
import IUT.RealVolumeTheory
import IUT.RealMaxLaws
import IUT.GaussPilotRep
import IUT.IntRealBridge
import IUT.TriSquare
import IUT.LambdaPropagation
import IUT.RegularPowers
import IUT.PolyWeierstrass
import IUT.GaloisClosureModel
import IUT.GSetQuotient
import IUT.RealInv
import IUT.LambdaValuation
import IUT.PolyDivision
import IUT.ApartInv
import IUT.RealRingLaws
import IUT.CosetGalois
import IUT.TowerSeparation
import IUT.RealFieldCapstone
import IUT.FactorialTower
import IUT.GaussPilotWeighted
import IUT.RealObstruction
import IUT.LambdaValuationMul
import IUT.RealDivision
import IUT.GeomSeries
import IUT.LambdaIdeal
import IUT.RealGeom
import IUT.RealPow
import IUT.RealPowMul
import IUT.RealGeomRec
import IUT.RealAbsPow
import IUT.GeomSeriesRec
import IUT.RealGeomCongr
import IUT.LambdaGeom
import IUT.RealAbsLe
import IUT.RealAbsTriangle
import IUT.RealGeomAbs
import IUT.LambdaInvApprox
import IUT.RealGeomInv
import IUT.GeometricSeriesProgram
import IUT.GeomDecayNat
import IUT.RealMulOrder
import IUT.RealGeomDecay
import IUT.GeomConverge
import IUT.GeomLimit
import IUT.GeomConvergeSC
import IUT.GaloisClosureLift
import IUT.EisSeparation
import IUT.AbstractEssSurj
import IUT.MuLIdentification
import IUT.GeomRlimComplete
import IUT.AbstractEssSurjSum
import IUT.ThetaHeisenbergLift
import IUT.TateCoverGroup
import IUT.AbstractGaloisDomination
import IUT.ThetaFuneqBridge
import IUT.MuP1Cyclic
import IUT.LambdaTowerGen
import IUT.EssSurjCapstone
import IUT.TateCoverCat
import IUT.MonoThetaEnv
import IUT.ConvergenceCapstone
import IUT.TateCoverGalois
import IUT.RecRamifiedSurj
import IUT.ThetaOperatorHom
import IUT.LogShell
import IUT.TateFiberFunctor
import IUT.Indeterminacies
import IUT.LambdaTowerTrans
import IUT.ThetaChainCapstone
import IUT.TateSurrogateCapstone
import IUT.RecUnramified
import IUT.ThetaValueEval
import IUT.LogKummer
import IUT.FormalEndRing
import IUT.Multiradial311
import IUT.PillarDFoundation
import IUT.MultiradialInput
import IUT.GaussPilot311
import IUT.RecSurjective
import IUT.ThetaEvalCapstone
import IUT.GaloisEquivalence
import IUT.ThetaLabelInjective
import IUT.LambdaTowerExactVal
import IUT.ProRepresentable
import IUT.PillarDInterface
import IUT.FormalGroupCapstone
import IUT.ThetaValueConstruct
import IUT.LambdaTowerRamif
import IUT.GaloisFullness
import IUT.LambdaTowerExactRamif
import IUT.InputConverse
import IUT.RealMultiradialInput
import IUT.GaloisEquivalenceBundle
import IUT.PillarDBetaLocalization
import IUT.FormalGroupPointLaws
import IUT.ThetaRingObject
import IUT.FrobenioidVolume
import IUT.GaloisEquivalenceUncond
import IUT.ThetaValueSubgroup
import IUT.NNQtoQHom
import IUT.LambdaTowerPiValBound
import IUT.GaloisFullnessConnected
import IUT.ArithPilot
import IUT.LambdaTowerRamifCapstone
import IUT.LambdaTowerPiValGeom
import IUT.LogVolEffMono
import IUT.ThetaValueProdLaws
import IUT.IndAction
import IUT.ThetaValueAlgebra
import IUT.ThetaLinkTransport
import IUT.FormalGroupPointOAction
import IUT.LambdaTowerResidueSurj
import IUT.GSetCoequalizer
import IUT.ThetaValueProdSwapAt
import IUT.IntermediateNormalCover
import IUT.FormalGroupPointODerived
import IUT.LambdaTowerResidueKernel
import IUT.TransportMirror
import IUT.ThetaValueProdBlockSwap
import IUT.FormalGroupOModulePoint
import IUT.LambdaTowerResidueKernelConverse
import IUT.NormalPairBoundary
import IUT.IndActionLabel
import IUT.PillarAFullnessProgram
import IUT.ThetaValueProdRangeSplit
import IUT.IndActionFull
import IUT.NNQOrder
import IUT.LambdaTowerResidueKernelTower
import IUT.Field
import IUT.QuotientGroup
import IUT.ProfiniteTopology
import IUT.PolyFieldDivision
import IUT.FractionField
import IUT.FieldAutGroup
import IUT.SeparablePoly
import IUT.FiniteEtaleAlgebra
import IUT.MinimalPolynomial
import IUT.SimpleExtension
import IUT.FiberFunctor
import IUT.EvaluationHom
import IUT.RootAdjunction
import IUT.GrothendieckGalois
import IUT.AlgebraTensor
import IUT.IdempotentSpectrum
import IUT.GaloisCorrespondence
import IUT.SeparableEmbeddings
import IUT.TowerLaw
import IUT.ConnectedEtale
import IUT.ProfinitePi1
import IUT.NormalSplitting
import IUT.GaloisPi1Iso
import IUT.GaloisFundamental
import IUT.PrimitiveElement
import IUT.SpecFunctorial
import IUT.ZariskiConnected
import IUT.PrimeSpectrum
import IUT.RingLocalization
import IUT.StructureSheafBasic
import IUT.FunctorOfPoints
import IUT.GlobalSectionsRecover
import IUT.LocalRingStalk
import IUT.ResidueField
import IUT.NilradicalReduced
import IUT.AffineEquivFull
import IUT.IntegralExtension
import IUT.FractionalIdeal
import IUT.RingOfIntegers
import IUT.ValuationRing
import IUT.DedekindDomain
import IUT.LocalFieldCompletion
import IUT.EllipticCurve
import IUT.EtaleThetaReal
import IUT.PicardDivisor
import IUT.EllipticJInvariant
import IUT.ThetaJacobi
import IUT.LogVolume
import IUT.TateCurve
import IUT.LocalFieldRing
import IUT.LogVolumeArch
import IUT.TateTorsion
import IUT.AlgClosureColimit
import IUT.FieldCompletion
import IUT.ThetaValueLtor
import IUT.ThetaPilotRealVolume
import IUT.KummerTheory
import IUT.MonoThetaRigidity
import IUT.LogShellReal
import IUT.CyclotomicRigidity
import IUT.AbsTopMultAdd
import IUT.GaussPilotRealVolume
import IUT.LogKummerReal
import IUT.ThetaLinkReal
import IUT.GaloisCohomologyH1
import IUT.AbsTopFieldRecover
import IUT.LocalReciprocity
import IUT.FrobenioidCategory
import IUT.IndeterminacyRealAction
import IUT.DiscreteRigidity
import IUT.LogLinkReal
import IUT.CyclotomeRecovery
import IUT.NormGroup
import IUT.ThetaCyclotomicRigidity
import IUT.HaarMeasureZp
import IUT.MeasureLogVolume
import IUT.Hilbert90
import IUT.IndeterminacyFull
import IUT.WeilPairing
import IUT.GaloisTheta
