/-
  宇宙際タイヒミュラー論 (IUT) 系3.12 の形式検証

  teichmuller/pdf/ の原論文 6 本を一次資料として、
  系3.12 をめぐる論争の形式骨格を Lean 4 で構成・検証する。
-/
import IUT.Arithmetic
import IUT.Skeleton
import IUT.ScholzeStix
import IUT.Mochizuki
import IUT.Boolean
import IUT.Verdict
import IUT.Anabelian
import IUT.HodgeTheater
import IUT.LogThetaLattice
import IUT.AbcConsequences
import IUT.Diophantine
import IUT.Multiradial
import IUT.Evaluation
import IUT.FundamentalGroup
import IUT.Reconstruction
import IUT.EtaleTheta
import IUT.Frobenioid
import IUT.Profinite
import IUT.GaloisCategory
import IUT.Topology
import IUT.SGA1
import IUT.Finiteness
import IUT.Compactness
import IUT.CategoryTheory
import IUT.GaloisAxioms
import IUT.AbstractGalois
import IUT.SGA1Completion
import IUT.SGA1Object
import IUT.ProObject
import IUT.LimitCompact
import IUT.SumDecomposition
import IUT.LocalCFT
import IUT.NormCorrespondence
import IUT.PrincipalUnits
import IUT.PrincipalUnitGroup
import IUT.UnitFiltration
import IUT.Fermat
import IUT.Teichmuller
import IUT.RootsOfUnity
import IUT.UnitDecomposition
import IUT.ZpUnits
import IUT.FullReciprocity
import IUT.Ring
import IUT.PowerSeries
import IUT.Composition
import IUT.LubinTateUnique
import IUT.LubinTateZp
import IUT.PadicDivision
import IUT.Binomial2
import IUT.Freshman
import IUT.PSFunctor
import IUT.FrobeniusCharP
import IUT.LTErrorDivisible
import IUT.LubinTateExists
import IUT.FrobenioidCat
import IUT.FrobenioidModel
import IUT.PolyIsomorphism
import IUT.PowerSeries2
import IUT.FormalGroupSub
import IUT.FormalGroupEq
import IUT.FormalGroupMap
import IUT.FrobeniusGen
import IUT.Frobenius2
